;;;; package.lisp

(defpackage #:varjo-lang
  (:use #:cl)
  (:export
   ;; variables
   :gl-max-clip-distances
   :gl-max-clip-planes
   :gl-max-draw-Buffers
   :gl-max-texture-units
   :gl-max-texture-coords
   :gl-max-geometry-texture-image-units
   :gl-max-texture-image-units
   :gl-max-vertex-attribs
   :gl-max-vertex-texture-image-units
   :gl-max-combined-texture-image-units
   :gl-max-geometry-varying-components
   :gl-max-varying-floats
   :gl-max-geometry-output-vertices
   :gl-max-fragment-uniform-components
   :gl-max-geometry-total-output-components
   :gl-max-geometry-uniform-components
   :gl-max-vertex-uniform-components
   :gl-vertex-id
   :gl-instance-id
   :gl-color
   :gl-secondary-color
   :gl-normal
   :gl-vertex
   :gl-multi-tex-coord-0
   :gl-multi-tex-coord-1
   :gl-multi-tex-coord-2
   :gl-multi-tex-coord-3
   :gl-multi-tex-coord-4
   :gl-multi-tex-coord-5
   :gl-multi-tex-coord-6
   :gl-multi-tex-coord-7
   :gl-fog-coord
   :gl-position
   :gl-point-size
   :gl-clip-distance
   :gl-clip-vertex
   :gl-front-color
   :gl-back-color
   :gl-front-secondary-color
   :gl-back-secondary-color
   :gl-tex-coord
   :gl-fog-frag-coord
   :gl-in
   :gl-primitive-id-in
   :gl-position
   :gl-primitive-id
   :gl-layer
   :gl-frag-coord
   :gl-front-facing
   :gl-clip-distance
   :gl-point-coord
   :gl-primitive-id
   :gl-frag-data
   :gl-frag-depth

   ;; special functions
   :setf-1
   :%assign
   :%return
   :labels-no-implicit
   :%out
   :%if
   :switch
   :for
   :while
   :swizzle
   :%break

   ;; macros in special.lisp
   :s~

   ;; functions
   :%*
   :%+
   :%-
   :%/
   :%<
   :%<=
   :%=
   :%>
   :%>=
   :%eql
   :%equal
   :++
   :--
   :all
   :any
   :atomic-counter
   :atomic-counter-decrement
   :atomic-counter-increment
   :barrier
   :bitfield-extract
   :bitfield-insert
   :bitfield-reverse
   :bool
   :ceil
   :clamp
   :cross
   :d-fdx
   :d-fdy
   :degrees
   :determinant
   :distance
   :dot
   :double
   :emit-stream-vertex
   :emit-vertex
   :end-primitive
   :end-stream-primitive
   :exp-2
   :faceforward
   :fma
   :fract
   :fwidth
   :greater-than
   :greater-than-equal
   :group-memory-barrier
   :image-atomic-add
   :image-atomic-and
   :image-atomic-comp-swap
   :image-atomic-exchange
   :image-atomic-max
   :image-atomic-min
   :image-atomic-or
   :image-atomic-xor
   :image-load
   :image-size
   :image-store
   :int
   :interpolate-at-centroid
   :interpolate-at-offset
   :interpolate-at-sample
   :inverse
   :inversesqrt
   :isinf
   :isnan
   :less-than
   :less-than-equal
   :log-2
   :m!
   :matrix-comp-mult
   :memory-barrier
   :memory-barrier-atomic-counter
   :memory-barrier-buffer
   :memory-barrier-image
   :memory-barrier-shared
   :mix
   :noise-1
   :normalize
   :not-equal
   :outer-product
   :pack-double-2x-3-2
   :pack-half-2x-1-6
   :pack-snorm-2x-1-6
   :pack-snorm-4x-8
   :pack-unorm-2x-1-6
   :pack-unorm-4x-8
   :pow
   :radians
   :reflect
   :refract
   :round-even
   :sign
   :smoothstep
   :transpose
   :trunc
   :uint
   :unpack-double-2x-3-2
   :unpack-half-2x-1-6
   :unpack-snorm-2x-1-6
   :unpack-snorm-4x-8
   :unpack-unorm-2x-1-6
   :unpack-unorm-4x-8
   :v!
   :v-equal
   :v-not
   :v-not-equal
   :w
   :x
   :y
   :z

   ;; texture functions
   :texel-fetch
   :texel-fetch-offset
   :texture
   :texture-grad
   :texture-grad-offset
   :texture-lod
   :texture-lod-offset
   :texture-offset
   :texture-proj
   :texture-proj-grad
   :texture-proj-grad-offset
   :texture-proj-lod
   :texture-proj-lod-offset
   :texture-proj-offset
   :texture-size))

(defpackage #:varjo
  (:use #:cl :varjo-lang :split-sequence #:alexandria #:cl-ppcre #:named-readtables)
  (:shadowing-import-from :varjo-lang :clamp :switch)
  (:export :v-glsl-size
           :v-casts-to-p
           :v-casts-to
           :find-mutual-cast-type

           ;;type functions
           :v-spec-typep
           :type-specp
           :type->type-spec
           :type-spec->type
           :v-glsl-size
           :v-type-eq
           :v-typep
           :v-casts-to-p
           :v-casts-to
           :find-mutual-cast-type
           :v-special-functionp
           :v-errorp

           ;;type accessors
           :core-typep
           :v-argument-spec
           :v-dimensions
           :v-element-type
           :v-fake-type
           :v-glsl-name
           :v-glsl-spec-matchingp
           :v-glsl-string
           :v-payload
           :v-restriction
           :v-return-spec
           :v-signature
           :v-slots
           :v-true-type

           ;;types
           :add-type-shadow
           :un-shadow
           :v-t-type
           :v-type
           :v-stemcell
           :v-spec-type
           :v-tfd
           :v-tf
           :v-td
           :v-tb
           :v-tiu
           :v-i-ui
           :v-ti
           :v-tu
           :v-tvec
           :v-array
           :v-none
           :v-function
	   :v-user-function
           :v-struct
           :v-user-struct
           :v-error
           :v-void
           :v-bool
           :v-number
           :v-int
           :v-uint
           :v-float
           :v-short-float
           :v-double
           :v-container
           :v-matrix
           :v-mat2
           :v-mat3
           :v-mat4
           :v-mat2x2
           :v-mat2x3
           :v-mat2x4
           :v-mat3x2
           :v-mat3x3
           :v-mat3x4
           :v-mat4x2
           :v-mat4x3
           :v-mat4x4
           :v-vector
           :v-fvector
           :v-vec2
           :v-vec3
           :v-vec4
           :v-bvector
           :v-bvec2
           :v-bvec3
           :v-bvec4
           :v-uvector
           :v-uvec2
           :v-uvec3
           :v-uvec4
           :v-ivector
           :v-ivec2
           :v-ivec3
           :v-ivec4
           :v-dvector
           :v-dvec2
           :v-dvec3
           :v-dvec4
           :v-sampler
           :v-isampler-1d
           :v-isampler-1d-array
           :v-isampler-2d
           :v-isampler-2d-array
           :v-isampler-2d-ms
           :v-isampler-2d-ms-array
           :v-isampler-2d-rect
           :v-isampler-3d
           :v-isampler-buffer
           :v-isampler-cube
           :v-isampler-cube-array
           :v-sampler-1d
           :v-sampler-1d-array
           :v-sampler-1d-array-shadow
           :v-sampler-1d-shadow
           :v-sampler-2d
           :v-sampler-2d-array
           :v-sampler-2d-array-shadow
           :v-sampler-2d-ms
           :v-sampler-2d-ms-array
           :v-sampler-2d-rect
           :v-sampler-2d-rect-shadow
           :v-sampler-2d-shadow
           :v-sampler-3d
           :v-sampler-buffer
           :v-sampler-cube
           :v-sampler-cube-array
           :v-sampler-cube-array-shadow
           :v-sampler-cube-shadow
           :v-usampler-1d
           :v-usampler-1d-array
           :v-usampler-2d
           :v-usampler-2d-array
           :v-usampler-2d-ms
           :v-usampler-2d-ms-array
           :v-usampler-2d-rect
           :v-usampler-3d
           :v-usampler-buffer
           :v-usampler-cube
           :v-usampler-cube-array

           ;;definitions
           :v-defstruct
           :v-defun
           :v-defmacro
           :v-define-compiler-macro
	   :add-equivalent-name

	   ;;flow-ids
	   :flow-id!
	   :id=
	   :id~=
	   :flow-ids

	   ;;environment
	   :get-var

	   ;; ast
	   :ast-node
	   :ast-node!
	   :visit-ast-nodes
	   :filter-ast-nodes
	   :walk-ast
	   :ast->code
	   :ast-starting-env
	   :ast-ending-env
	   :ast-kind
	   :ast-kindp
	   :ast-typep
	   :ast-return-type
	   :ast-flow-id
	   :ast-flow-id-origin
	   :ast-val-origin
	   :ast-args
	   :ast-parent
	   :flow-id-orgins
	   :val-origins

           ;;compiler
           :compile-form
           :with-stemcell-infer-hook

           ;;front-end
           :translate
           :rolling-translate
           :split-arguments
           :v-macroexpand-all
           :v-compiler-macroexpand-all
           :*stage-types*

           ;;compile-result
	   :glsl-code
	   :stage-type
	   :out-vars
	   :in-args
	   :uniforms
	   :implicit-uniforms
	   :context
	   :used-macros
	   :used-compiler-macros
	   :used-symbol-macros
	   :ast
	   :third-party-metadata

           ;;utils
           :lambda-list-split
           :pipe->))
