;; This software is Copyright (c) 2012 Chris Bagley
;; (techsnuffle<at>gmail<dot>com)
;; Chris Bagley grants you the rights to
;; distribute and use this software as governed
;; by the terms of the Lisp Lesser GNU Public License
;; (http://opensource.franz.com/preamble.html),
;; known as the LLGPL.
(in-package :varjo)

(defmethod v-type-name ((type v-type))
  (class-name (class-of type)))

(defclass v-array (v-container) 
  ((element-type :initform nil :initarg :element-type :reader v-element-type)
   (dimensions :initform nil :initarg :dimensions :reader v-dimensions)))

(defun type-spec->type (spec)  
  (if (symbolp spec)
      (make-instance (if (keywordp spec) (symb 'v- spec) spec))
      (destructuring-bind (type dimensions) spec
        (make-instance 'v-array :element-type (if (keywordp spec) 
                                                  (symb 'v- type)
                                                  type)
                       :dimensions dimensions))))

(defmethod v-glsl-size ((type t))
  (slot-value type 'glsl-size))

(defmethod v-glsl-size ((type v-array))
  (* (apply #'* (v-dimensions type)) 
     (slot-value (v-element-type type) 'glsl-size)))

(defmethod v-casts-to-p ((from-type v-type) (to-type symbol))
  (or (eq from-type to-type)
      (find to-type (slot-value from-type 'casts-to))))

(defmethod v-casts-to-p ((from-type symbol) (to-type symbol))
  (not (null (or (eq from-type to-type)
                 (let ((from-type (make-instance from-type)))
                   (find to-type (slot-value from-type 'casts-to)))))))

(defun find-mutual-cast-type (&rest types)
  (let ((casts (loop :for type :in types :collect 
                  (if (symbolp type) 
                      (cons type (slot-value (make-instance type) 'casts-to)) 
                      (cons (v-type-name type) 
                            (slot-value type 'casts-to))))))
    (destructuring-bind (mutual-casts . other-cast-lists) casts
      (loop :for casts :in other-cast-lists :do
         (setf mutual-casts (intersection mutual-casts casts)))
      (first (sort mutual-casts #'v-superior)))))

(let ((order-or-superiority '(v-double v-float v-int v-uint v-vec2 v-ivec2 
                              v-uvec2 v-vec3 v-ivec3 v-uvec3 v-vec4 v-ivec4
                              v-uvec4 v-mat2 v-mat2x2 v-mat3 v-mat3x3 v-mat4
                              v-mat4x4)))
  (defun v-superior (x y) 
    (< (or (position x order-or-superiority) -1)
       (or (position y order-or-superiority) -1))))

(defun v-superior-type (&rest types)
  (first (sort mutual-casts #'v-superior)))

(defclass v-none () ())

(defclass v-function (v-type)
  ((restriction :initform nil :initarg :restriction :accessor v-restriction)
   (argument-spec :initform nil :initarg :arg-spec :accessor v-argument-spec)
   (code :initform nil :initarg :code :accessor v-code)
   (glsl-string :initform "" :initarg :glsl-string :reader v-glsl-string)
   (return-spec :initform nil :initarg :return-spec :accessor v-return-spec)
   (place :initform nil :initarg :place :accessor v-placep)))

(defgeneric v-special-functionp (func))
(defmethod v-special-functionp ((func function))
  (eq :special (v-glsl-string func)))

(defclass v-void () 
  ((core :initform t :reader core-typep)
   (glsl-string :initform "" :reader v-glsl-string)))

(defclass v-bool (v-type) 
  ((core :initform t :reader core-typep)
   (glsl-string :initform "bool" :reader v-glsl-string)))

(defclass v-number (v-type) ())
(defclass v-int (v-number) 
  ((core :initform t :reader core-typep)
   (glsl-string :initform "int" :reader v-glsl-string)
   (casts-to :initform '(v-uint v-float v-double))))
(defclass v-uint (v-number) 
  ((core :initform t :reader core-typep)
   (glsl-string :initform "uint" :reader v-glsl-string)
   (casts-to :initform '(v-float v-double))))
(defclass v-float (v-number) 
  ((core :initform t :reader core-typep)
   (glsl-string :initform "float" :reader v-glsl-string)
   (casts-to :initform '(v-double))))
(defclass v-short-float (v-number) 
  ((core :initform t :reader core-typep)
   (glsl-string :initform "short-float" :reader v-glsl-string)))
(defclass v-double (v-number) 
  ((core :initform t :reader core-typep)
   (glsl-string :initform "double" :reader v-glsl-string)))

(defclass v-container (v-type)
  ((element-type :initform nil :reader v-element-type)
   (dimensions :initform nil :reader v-dimensions)))

(defclass v-matrix (v-container) ())
(defclass v-mat2 (v-matrix) 
  ((core :initform t :reader core-typep)
   (glsl-string :initform "mat2" :reader v-glsl-string)
   (element-type :initform 'v-float :reader v-element-type)
   (dimensions :initform '(2 2) :reader v-dimensions)
   (glsl-size :initform 2)
   (casts-to :initform '(v-dmat2))))
(defclass v-mat3 (v-matrix) 
  ((core :initform t :reader core-typep)
   (glsl-string :initform "mat3" :reader v-glsl-string)
   (element-type :initform 'v-float :reader v-element-type)
   (dimensions :initform '(3 3) :reader v-dimensions)
   (glsl-size :initform 3)
   (casts-to :initform '(v-dmat3))))
(defclass v-mat4 (v-matrix) 
  ((core :initform t :reader core-typep)
   (glsl-string :initform "mat4" :reader v-glsl-string)
   (element-type :initform 'v-float :reader v-element-type)
   (dimensions :initform '(4 4) :reader v-dimensions)
   (glsl-size :initform 4)
   (casts-to :initform '(v-dmat4))))
(DEFCLASS V-MAT2X2 (V-MATRIX)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "mat2x2" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-FLOAT :READER V-ELEMENT-TYPE)
   (dimensions :initform '(2 2) :reader v-dimensions)
   (glsl-size :initform 2)))
(DEFCLASS V-MAT2X3 (V-MATRIX)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "mat2x3" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-FLOAT :READER V-ELEMENT-TYPE)
   (dimensions :initform '(2 3) :reader v-dimensions)
   (glsl-size :initform 2)
   (casts-to :initform '(v-dmat2x3))))
(DEFCLASS V-MAT2X4 (V-MATRIX)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "mat2x4" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-FLOAT :READER V-ELEMENT-TYPE)
   (dimensions :initform '(2 4) :reader v-dimensions)
   (glsl-size :initform 2)
   (casts-to :initform '(v-dmat2x4))))
(DEFCLASS V-MAT3X2 (V-MATRIX)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "mat3x2" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-FLOAT :READER V-ELEMENT-TYPE)
   (dimensions :initform '(3 2) :reader v-dimensions)
   (glsl-size :initform 3)
   (casts-to :initform '(v-dmat3x2))))
(DEFCLASS V-MAT3X3 (V-MATRIX)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "mat3x3" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-FLOAT :READER V-ELEMENT-TYPE)
   (dimensions :initform '(3 3) :reader v-dimensions)
   (glsl-size :initform 3)))
(DEFCLASS V-MAT3X4 (V-MATRIX)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "mat3x4" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-FLOAT :READER V-ELEMENT-TYPE)
   (dimensions :initform '(3 4) :reader v-dimensions)
   (glsl-size :initform 3)
   (casts-to :initform '(v-dmat3x4))))
(DEFCLASS V-MAT4X2 (V-MATRIX)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "mat4x2" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-FLOAT :READER V-ELEMENT-TYPE)
   (dimensions :initform '(4 2) :reader v-dimensions)
   (glsl-size :initform 4)
   (casts-to :initform '(v-dmat4x2))))
(DEFCLASS V-MAT4X3 (V-MATRIX)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "mat4x3" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-FLOAT :READER V-ELEMENT-TYPE)
   (dimensions :initform '(4 3) :reader v-dimensions)
   (glsl-size :initform 4)
   (casts-to :initform '(v-dmat4x3))))
(DEFCLASS V-MAT4X4 (V-MATRIX)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "mat4x4" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-FLOAT :READER V-ELEMENT-TYPE)
   (dimensions :initform '(4 4) :reader v-dimensions)
   (glsl-size :initform 4)))

(defclass v-vector (v-container) ())
(defclass v-fvector (v-vector) ())
(defclass v-vec2 (v-fvector) 
  ((core :initform t :reader core-typep)
   (glsl-string :initform "vec2" :reader v-glsl-string)
   (element-type :initform 'v-float :reader v-element-type)
   (dimensions :initform '(2) :reader v-dimensions)
   (casts-to :initform '(v-dvec2))))
(defclass v-vec3 (v-fvector) 
  ((core :initform t :reader core-typep)
   (glsl-string :initform "vec3" :reader v-glsl-string)
   (element-type :initform 'v-float :reader v-element-type)
   (dimensions :initform '(3) :reader v-dimensions)
   (casts-to :initform '(v-dvec3))))
(defclass v-vec4 (v-fvector) 
  ((core :initform t :reader core-typep)
   (glsl-string :initform "vec4" :reader v-glsl-string)
   (element-type :initform 'v-float :reader v-element-type)
   (dimensions :initform '(4) :reader v-dimensions)
   (casts-to :initform '(v-dvec4))))

(defclass v-bvector (v-vector) ())
(defclass v-bvec2 (v-bvector) 
  ((core :initform t :reader core-typep)
   (glsl-string :initform "bvec2" :reader v-glsl-string)
   (element-type :initform 'v-bool :reader v-element-type)
   (dimensions :initform '(2) :reader v-dimensions)))
(defclass v-bvec3 (v-bvector) 
  ((core :initform t :reader core-typep)
   (glsl-string :initform "bvec3" :reader v-glsl-string)
   (element-type :initform 'v-bool :reader v-element-type)
   (dimensions :initform '(3) :reader v-dimensions)))
(defclass v-bvec4 (v-bvector) 
  ((core :initform t :reader core-typep)
   (glsl-string :initform "bvec4" :reader v-glsl-string)
   (element-type :initform 'v-bool :reader v-element-type)
   (dimensions :initform '(4) :reader v-dimensions)))

(defclass v-uvector (v-vector) ())
(defclass v-uvec2 (v-uvector) 
  ((core :initform t :reader core-typep)
   (glsl-string :initform "uvec2" :reader v-glsl-string)
   (element-type :initform 'v-uint :reader v-element-type)
   (dimensions :initform '(2) :reader v-dimensions)
   (casts-to :initform '(v-dvec2 v-vec2))))
(defclass v-uvec3 (v-uvector) 
  ((core :initform t :reader core-typep)
   (glsl-string :initform "uvec3" :reader v-glsl-string)
   (element-type :initform 'v-uint :reader v-element-type)
   (dimensions :initform '(3) :reader v-dimensions)
   (casts-to :initform '(v-dvec3 v-vec3))))
(defclass v-uvec4 (v-uvector) 
  ((core :initform t :reader core-typep)
   (glsl-string :initform "uvec4" :reader v-glsl-string)
   (element-type :initform 'v-uint :reader v-element-type)
   (dimensions :initform '(4) :reader v-dimensions)
   (casts-to :initform '(v-dvec4 v-vec4))))

(defclass v-ivector (v-vector) ())
(defclass v-ivec2 (v-ivector) 
  ((core :initform t :reader core-typep)
   (glsl-string :initform "ivec2" :reader v-glsl-string)
   (element-type :initform 'v-int :reader v-element-type)
   (dimensions :initform '(2) :reader v-dimensions)
   (casts-to :initform '(v-uvec2 v-vec2 v-dvec2))))
(defclass v-ivec3 (v-ivector) 
  ((core :initform t :reader core-typep)
   (glsl-string :initform "ivec3" :reader v-glsl-string)
   (element-type :initform 'v-int :reader v-element-type)
   (dimensions :initform '(3) :reader v-dimensions)
   (casts-to :initform '(v-uvec3 v-vec3 v-dvec3))))
(defclass v-ivec4 (v-ivector) 
  ((core :initform t :reader core-typep)
   (glsl-string :initform "ivec4" :reader v-glsl-string)
   (element-type :initform 'v-int :reader v-element-type)
   (dimensions :initform '(4) :reader v-dimensions)
   (casts-to :initform '(v-uvec4 v-vec4 v-dvec4))))

(defclass v-sampler (v-type) ())
(DEFCLASS V-ISAMPLER-1D (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "isampler-1D" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-ISAMPLER-1D-ARRAY (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "isampler-1d-Array" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-ISAMPLER-2D (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "isampler-2D" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-ISAMPLER-2D-ARRAY (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "isampler-2d-Array" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-ISAMPLER-2D-MS (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "isampler-2d-MS" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-ISAMPLER-2D-MS-ARRAY (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "isampler-2d-MS-Array" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-ISAMPLER-2D-RECT (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "isampler-2d-Rect" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-ISAMPLER-3D (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "isampler-3d" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-ISAMPLER-BUFFER (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "isampler-Buffer" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-ISAMPLER-CUBE (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "isampler-Cube" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-ISAMPLER-CUBE-ARRAY (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "isampler-Cube-Array" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-SAMPLER-1D (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "sampler-1D" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-SAMPLER-1D-ARRAY (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "sampler-1d-Array" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-SAMPLER-1D-ARRAY-SHADOW (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "sampler-1d-Array-Shadow" :READER
                GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-SAMPLER-1D-SHADOW (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "sampler-1d-Shadow" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-SAMPLER-2D (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "sampler-2D" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-SAMPLER-2D-ARRAY (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "sampler-2d-Array" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-SAMPLER-2D-ARRAY-SHADOW (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "sampler-2d-Array-Shadow" :READER
                GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-SAMPLER-2D-MS (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "sampler-2d-MS" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-SAMPLER-2D-MS-ARRAY (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "sampler-2d-MS-Array" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-SAMPLER-2D-RECT (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "sampler-2d-Rect" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-SAMPLER-2D-RECT-SHADOW (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "sampler-2d-Rect-Shadow" :READER
                GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-SAMPLER-2D-SHADOW (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "sampler-2d-Shadow" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-SAMPLER-3D (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "sampler-3d" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-SAMPLER-BUFFER (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "sampler-Buffer" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-SAMPLER-CUBE (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "sampler-Cube" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-SAMPLER-CUBE-ARRAY (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "sampler-Cube-Array" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-SAMPLER-CUBE-ARRAY-SHADOW (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "sampler-Cube-Array-Shadow" :READER
                GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-SAMPLER-CUBE-SHADOW (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "sampler-Cube-Shadow" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-USAMPLER-1D (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "usampler-1D" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-USAMPLER-1D-ARRAY (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "usampler-1d-Array" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-USAMPLER-2D (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "usampler-2D" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-USAMPLER-2D-ARRAY (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "usampler-2d-Array" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-USAMPLER-2D-MS (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "usampler-2d-MS" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-USAMPLER-2D-MS-ARRAY (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "usampler-2d-MS-Array" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-USAMPLER-2D-RECT (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "usampler-2d-Rect" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-USAMPLER-3D (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "usampler-3d" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-USAMPLER-BUFFER (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "usampler-Buffer" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-USAMPLER-CUBE (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "usampler-Cube" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))
(DEFCLASS V-USAMPLER-CUBE-ARRAY (V-SAMPLER)
  ((CORE :INITFORM T :READER CORE-TYPEP)
   (GLSL-STRING :INITFORM "usampler-Cube-Array" :READER V-GLSL-STRING)
   (ELEMENT-TYPE :INITFORM 'V-VEC4 :READER V-ELEMENT-TYPE)))

;;----------v-v-v-old-v-v-v-----------;
;; [TODO] why only first 2?
;; (defun type-equal (a b)
;;   (equal (subseq a 0 2) (subseq b 0 2)))

