'((("int" "textureSize") (("gsampler1D" "sampler") ("int" "lod")))
  (("ivec2" "textureSize") (("gsampler2D" "sampler") ("int" "lod")))
  (("ivec3" "textureSize") (("gsampler3D" "sampler") ("int" "lod")))
  (("ivec2" "textureSize") (("gsamplerCube" "sampler") ("int" "lod")))
  (("int" "textureSize") (("sampler1DShadow" "sampler") ("int" "lod")))
  (("ivec2" "textureSize") (("sampler2DShadow" "sampler") ("int" "lod")))
  (("ivec2" "textureSize") (("samplerCubeShadow" "sampler") ("int" "lod")))
  (("ivec2" "textureSize") (("gsampler2DRect" "sampler")))
  (("ivec2" "textureSize") (("sampler2DRectShadow" "sampler")))
  (("ivec2" "textureSize") (("gsampler1DArray" "sampler") ("int" "lod")))
  (("ivec3" "textureSize") (("gsampler2DArray" "sampler") ("int" "lod")))
  (("ivec2" "textureSize") (("sampler1DArrayShadow" "sampler") ("int" "lod")))
  (("ivec3" "textureSize") (("sampler2DArrayShadow" "sampler") ("int" "lod")))
  (("int" "textureSize") (("gsamplerBuffer" "sampler")))
  (("ivec2" "textureSize") (("gsampler2DMS" "sampler")))
  (("ivec2" "textureSize") (("gsampler2DMSArray" "sampler")))
  (("gvec4" "texture")
   (("gsampler1D" "sampler") ("float" "P") (("float" "bias"))))
  (("gvec4" "texture")
   (("gsampler2D" "sampler") ("vec2" "P") (("float" "bias"))))
  (("gvec4" "texture")
   (("gsampler3D" "sampler") ("vec3" "P") (("float" "bias"))))
  (("gvec4" "texture")
   (("gsamplerCube" "sampler") ("vec3" "P") (("float" "bias"))))
  (("float" "texture")
   (("sampler1DShadow" "sampler") ("vec3" "P") (("float" "bias"))))
  (("float" "texture")
   (("sampler2DShadow" "sampler") ("vec3" "P") (("float" "bias"))))
  (("float" "texture")
   (("samplerCubeShadow" "sampler") ("vec4" "P") (("float" "bias"))))
  (("gvec4" "texture")
   (("gsampler1DArray" "sampler") ("vec2" "P") (("float" "bias"))))
  (("gvec4" "texture")
   (("gsampler2DArray" "sampler") ("vec3" "P") (("float" "bias"))))
  (("float" "texture")
   (("sampler1DArrayShadow" "sampler") ("vec3" "P") (("float" "bias"))))
  (("float" "texture") (("sampler2DArrayShadow" "sampler") ("vec4" "P")))
  (("gvec4" "texture") (("gsampler2DRect" "sampler") ("vec2" "P")))
  (("float" "texture") (("sampler2DRectShadow" "sampler") ("vec3" "P")))
  (("gvec4" "textureProj")
   (("gsampler1D" "sampler") ("vec2" "P") (("float" "bias"))))
  (("gvec4" "textureProj")
   (("gsampler1D" "sampler") ("vec4" "P") (("float" "bias"))))
  (("gvec4" "textureProj")
   (("gsampler2D" "sampler") ("vec3" "P") (("float" "bias"))))
  (("gvec4" "textureProj")
   (("gsampler2D" "sampler") ("vec4" "P") (("float" "bias"))))
  (("gvec4" "textureProj")
   (("gsampler3D" "sampler") ("vec4" "P") (("float" "bias"))))
  (("float" "textureProj")
   (("sampler1DShadow" "sampler") ("vec4" "P") (("float" "bias"))))
  (("float" "textureProj")
   (("sampler2DShadow" "sampler") ("vec4" "P") (("float" "bias"))))
  (("gvec4" "textureProj") (("gsampler2DRect" "sampler") ("vec3" "P")))
  (("gvec4" "textureProj") (("gsampler2DRect" "sampler") ("vec4" "P")))
  (("float" "textureProj") (("sampler2DRectShadow" "sampler") ("vec4" "P")))
  (("gvec4" "textureLod")
   (("gsampler1D" "sampler") ("float" "P") ("float" "lod")))
  (("gvec4" "textureLod")
   (("gsampler2D" "sampler") ("vec2" "P") ("float" "lod")))
  (("gvec4" "textureLod")
   (("gsampler3D" "sampler") ("vec3" "P") ("float" "lod")))
  (("gvec4" "textureLod")
   (("gsamplerCube" "sampler") ("vec3" "P") ("float" "lod")))
  (("float" "textureLod")
   (("sampler1DShadow" "sampler") ("vec3" "P") ("float" "lod")))
  (("float" "textureLod")
   (("sampler2DShadow" "sampler") ("vec3" "P") ("float" "lod")))
  (("gvec4" "textureLod")
   (("gsampler1DArray" "sampler") ("vec2" "P") ("float" "lod")))
  (("gvec4" "textureLod")
   (("gsampler2DArray" "sampler") ("vec3" "P") ("float" "lod")))
  (("float" "textureLod")
   (("sampler1DArrayShadow" "sampler") ("vec3" "P") ("float" "lod")))
  (("gvec4" "textureOffset")
   (("gsampler1D" "sampler") ("float" "P") ("int" "offset")
    (("float" "bias"))))
  (("gvec4" "textureOffset")
   (("gsampler2D" "sampler") ("vec2" "P") ("ivec2" "offset")
    (("float" "bias"))))
  (("gvec4" "textureOffset")
   (("gsampler3D" "sampler") ("vec3" "P") ("ivec3" "offset")
    (("float" "bias"))))
  (("gvec4" "textureOffset")
   (("gsampler2DRect" "sampler") ("vec2" "P") ("ivec2" "offset")))
  (("float" "textureOffset")
   (("sampler2DRectShadow" "sampler") ("vec3" "P") ("ivec2" "offset")))
  (("float" "textureOffset")
   (("sampler1DShadow" "sampler") ("vec3" "P") ("int" "offset")
    (("float" "bias"))))
  (("float" "textureOffset")
   (("sampler2DShadow" "sampler") ("vec3" "P") ("ivec2" "offset")
    (("float" "bias"))))
  (("gvec4" "textureOffset")
   (("gsampler1DArray" "sampler") ("vec2" "P") ("int" "offset")
    (("float" "bias"))))
  (("gvec4" "textureOffset")
   (("gsampler2DArray" "sampler") ("vec3" "P") ("ivec2" "offset")
    (("float" "bias"))))
  (("float" "textureOffset")
   (("sampler1DArrayShadow" "sampler") ("vec3" "P") ("int" "offset")
    (("float" "bias"))))
  (("gvec4" "texelFetch") (("gsampler1D" "sampler") ("int" "P") ("int" "lod")))
  (("gvec4" "texelFetch")
   (("gsampler2D" "sampler") ("ivec2" "P") ("int" "lod")))
  (("gvec4" "texelFetch")
   (("gsampler3D" "sampler") ("ivec3" "P") ("int" "lod")))
  (("gvec4" "texelFetch") (("gsampler2DRect" "sampler") ("ivec2" "P")))
  (("gvec4" "texelFetch")
   (("gsampler1DArray" "sampler") ("ivec2" "P") ("int" "lod")))
  (("gvec4" "texelFetch")
   (("gsampler2DArray" "sampler") ("ivec3" "P") ("int" "lod")))
  (("gvec4" "texelFetch") (("gsamplerBuffer" "sampler") ("int" "P")))
  (("gvec4" "texelFetch")
   (("gsampler2DMS" "sampler") ("ivec2" "P") ("int" "sample")))
  (("gvec4" "texelFetch")
   (("gsampler2DMSArray" "sampler") ("ivec3" "P") ("int" "sample")))
  (("gvec4" "texelFetchOffset")
   (("gsampler1D" "sampler") ("int" "P") ("int" "lod") ("int" "offset")))
  (("gvec4" "texelFetchOffset")
   (("gsampler2D" "sampler") ("ivec2" "P") ("int" "lod") ("ivec2" "offset")))
  (("gvec4" "texelFetchOffset")
   (("gsampler3D" "sampler") ("ivec3" "P") ("int" "lod") ("ivec3" "offset")))
  (("gvec4" "texelFetchOffset")
   (("gsampler2DRect" "sampler") ("ivec2" "P") ("ivec2" "offset")))
  (("gvec4" "texelFetchOffset")
   (("gsampler1DArray" "sampler") ("ivec2" "P") ("int" "lod") ("int" "offset")))
  (("gvec4" "texelFetchOffset")
   (("gsampler2DArray" "sampler") ("ivec3" "P") ("int" "lod")
    ("ivec2" "offset")))
  (("gvec4" "textureProjOffset")
   (("gsampler1D" "sampler") ("vec2" "P") ("int" "offset")
    (("float" "bias"))))
  (("gvec4" "textureProjOffset")
   (("gsampler1D" "sampler") ("vec4" "P") ("int" "offset")
    (("float" "bias"))))
  (("gvec4" "textureProjOffset")
   (("gsampler2D" "sampler") ("vec3" "P") ("ivec2" "offset")
    (("float" "bias"))))
  (("gvec4" "textureProjOffset")
   (("gsampler2D" "sampler") ("vec4" "P") ("ivec2" "offset")
    (("float" "bias"))))
  (("gvec4" "textureProjOffset")
   (("gsampler3D" "sampler") ("vec4" "P") ("ivec3" "offset")
    (("float" "bias"))))
  (("gvec4" "textureProjOffset")
   (("gsampler2DRect" "sampler") ("vec3" "P") ("ivec2" "offset")))
  (("gvec4" "textureProjOffset")
   (("gsampler2DRect" "sampler") ("vec4" "P") ("ivec2" "offset")))
  (("float" "textureProjOffset")
   (("sampler2DRectShadow" "sampler") ("vec4" "P") ("ivec2" "offset")))
  (("float" "textureProjOffset")
   (("sampler1DShadow" "sampler") ("vec4" "P") ("int" "offset")
    (("float" "bias"))))
  (("float" "textureProjOffset")
   (("sampler2DShadow" "sampler") ("vec4" "P") ("ivec2" "offset")
    (("float" "bias"))))
  (("gvec4" "textureLodOffset")
   (("gsampler1D" "sampler") ("float" "P") ("float" "lod") ("int" "offset")))
  (("gvec4" "textureLodOffset")
   (("gsampler2D" "sampler") ("vec2" "P") ("float" "lod") ("ivec2" "offset")))
  (("gvec4" "textureLodOffset")
   (("gsampler3D" "sampler") ("vec3" "P") ("float" "lod") ("ivec3" "offset")))
  (("float" "textureLodOffset")
   (("sampler1DShadow" "sampler") ("vec3" "P") ("float" "lod")
    ("int" "offset")))
  (("float" "textureLodOffset")
   (("sampler2DShadow" "sampler") ("vec3" "P") ("float" "lod")
    ("ivec2" "offset")))
  (("gvec4" "textureLodOffset")
   (("gsampler1DArray" "sampler") ("vec2" "P") ("float" "lod")
    ("int" "offset")))
  (("gvec4" "textureLodOffset")
   (("gsampler2DArray" "sampler") ("vec3" "P") ("float" "lod")
    ("ivec2" "offset")))
  (("float" "textureLodOffset")
   (("sampler1DArrayShadow" "sampler") ("vec3" "P") ("float" "lod")
    ("int" "offset")))
  (("gvec4" "textureProjLod")
   (("gsampler1D" "sampler") ("vec2" "P") ("float" "lod")))
  (("gvec4" "textureProjLod")
   (("gsampler1D" "sampler") ("vec4" "P") ("float" "lod")))
  (("gvec4" "textureProjLod")
   (("gsampler2D" "sampler") ("vec3" "P") ("float" "lod")))
  (("gvec4" "textureProjLod")
   (("gsampler2D" "sampler") ("vec4" "P") ("float" "lod")))
  (("gvec4" "textureProjLod")
   (("gsampler3D" "sampler") ("vec4" "P") ("float" "lod")))
  (("float" "textureProjLod")
   (("sampler1DShadow" "sampler") ("vec4" "P") ("float" "lod")))
  (("float" "textureProjLod")
   (("sampler2DShadow" "sampler") ("vec4" "P") ("float" "lod")))
  (("gvec4" "textureProjLodOffset")
   (("gsampler1D" "sampler") ("vec2" "P") ("float" "lod") ("int" "offset")))
  (("gvec4" "textureProjLodOffset")
   (("gsampler1D" "sampler") ("vec4" "P") ("float" "lod") ("int" "offset")))
  (("gvec4" "textureProjLodOffset")
   (("gsampler2D" "sampler") ("vec3" "P") ("float" "lod") ("ivec2" "offset")))
  (("gvec4" "textureProjLodOffset")
   (("gsampler2D" "sampler") ("vec4" "P") ("float" "lod") ("ivec2" "offset")))
  (("gvec4" "textureProjLodOffset")
   (("gsampler3D" "sampler") ("vec4" "P") ("float" "lod") ("ivec3" "offset")))
  (("float" "textureProjLodOffset")
   (("sampler1DShadow" "sampler") ("vec4" "P") ("float" "lod")
    ("int" "offset")))
  (("float" "textureProjLodOffset")
   (("sampler2DShadow" "sampler") ("vec4" "P") ("float" "lod")
    ("ivec2" "offset")))
  (("gvec4" "textureGrad")
   (("gsampler1D" "sampler") ("float" "P") ("float" "dPdx") ("float" "dPdy")))
  (("gvec4" "textureGrad")
   (("gsampler2D" "sampler") ("vec2" "P") ("vec2" "dPdx") ("vec2" "dPdy")))
  (("gvec4" "textureGrad")
   (("gsampler3D" "sampler") ("vec3" "P") ("vec3" "dPdx") ("vec3" "dPdy")))
  (("gvec4" "textureGrad")
   (("gsamplerCube" "sampler") ("vec3" "P") ("vec3" "dPdx") ("vec3" "dPdy")))
  (("gvec4" "textureGrad")
   (("gsampler2DRect" "sampler") ("vec2" "P") ("vec2" "dPdx") ("vec2" "dPdy")))
  (("float" "textureGrad")
   (("sampler2DRectShadow" "sampler") ("vec3" "P") ("vec2" "dPdx")
    ("vec2" "dPdy")))
  (("float" "textureGrad")
   (("sampler1DShadow" "sampler") ("vec3" "P") ("float" "dPdx")
    ("float" "dPdy")))
  (("float" "textureGrad")
   (("sampler2DShadow" "sampler") ("vec3" "P") ("vec2" "dPdx") ("vec2" "dPdy")))
  (("float" "textureGrad")
   (("samplerCubeShadow" "sampler") ("vec4" "P") ("vec3" "dPdx")
    ("vec3" "dPdy")))
  (("gvec4" "textureGrad")
   (("gsampler1DArray" "sampler") ("vec2" "P") ("float" "dPdx")
    ("float" "dPdy")))
  (("gvec4" "textureGrad")
   (("gsampler2DArray" "sampler") ("vec3" "P") ("vec2" "dPdx") ("vec2" "dPdy")))
  (("float" "textureGrad")
   (("sampler1DArrayShadow" "sampler") ("vec3" "P") ("float" "dPdx")
    ("float" "dPdy")))
  (("float" "textureGrad")
   (("sampler2DArrayShadow" "sampler") ("vec4" "P") ("vec2" "dPdx")
    ("vec2" "dPdy")))
  (("gvec4" "textureGradOffset")
   (("gsampler1D" "sampler") ("float" "P") ("float" "dPdx") ("float" "dPdy")
    ("int" "offset")))
  (("gvec4" "textureGradOffset")
   (("gsampler2D" "sampler") ("vec2" "P") ("vec2" "dPdx") ("vec2" "dPdy")
    ("ivec2" "offset")))
  (("gvec4" "textureGradOffset")
   (("gsampler3D" "sampler") ("vec3" "P") ("vec3" "dPdx") ("vec3" "dPdy")
    ("ivec3" "offset")))
  (("gvec4" "textureGradOffset")
   (("gsampler2DRect" "sampler") ("vec2" "P") ("vec2" "dPdx") ("vec2" "dPdy")
    ("ivec2" "offset")))
  (("float" "textureGradOffset")
   (("sampler2DRectShadow" "sampler") ("vec3" "P") ("vec2" "dPdx")
    ("vec2" "dPdy") ("ivec2" "offset")))
  (("float" "textureGradOffset")
   (("sampler1DShadow" "sampler") ("vec3" "P") ("float" "dPdx") ("float" "dPdy")
    ("int" "offset")))
  (("float" "textureGradOffset")
   (("sampler2DShadow" "sampler") ("vec3" "P") ("vec2" "dPdx") ("vec2" "dPdy")
    ("ivec2" "offset")))
  (("gvec4" "textureGradOffset")
   (("gsampler1DArray" "sampler") ("vec2" "P") ("float" "dPdx") ("float" "dPdy")
    ("int" "offset")))
  (("gvec4" "textureGradOffset")
   (("gsampler2DArray" "sampler") ("vec3" "P") ("vec2" "dPdx") ("vec2" "dPdy")
    ("ivec2" "offset")))
  (("float" "textureGradOffset")
   (("sampler1DArrayShadow" "sampler") ("vec3" "P") ("float" "dPdx")
    ("float" "dPdy") ("int" "offset")))
  (("float" "textureGradOffset")
   (("sampler2DArrayShadow" "sampler") ("vec4" "P") ("vec2" "dPdx")
    ("vec2" "dPdy") ("ivec2" "offset")))
  (("gvec4" "textureProjGrad")
   (("gsampler1D" "sampler") ("vec2" "P") ("float" "dPdx") ("float" "dPdy")))
  (("gvec4" "textureProjGrad")
   (("gsampler1D" "sampler") ("vec4" "P") ("float" "dPdx") ("float" "dPdy")))
  (("gvec4" "textureProjGrad")
   (("gsampler2D" "sampler") ("vec3" "P") ("vec2" "dPdx") ("vec2" "dPdy")))
  (("gvec4" "textureProjGrad")
   (("gsampler2D" "sampler") ("vec4" "P") ("vec2" "dPdx") ("vec2" "dPdy")))
  (("gvec4" "textureProjGrad")
   (("gsampler3D" "sampler") ("vec4" "P") ("vec3" "dPdx") ("vec3" "dPdy")))
  (("gvec4" "textureProjGrad")
   (("gsampler2DRect" "sampler") ("vec3" "P") ("vec2" "dPdx") ("vec2" "dPdy")))
  (("gvec4" "textureProjGrad")
   (("gsampler2DRect" "sampler") ("vec4" "P") ("vec2" "dPdx") ("vec2" "dPdy")))
  (("float" "textureProjGrad")
   (("sampler2DRectShadow" "sampler") ("vec4" "P") ("vec2" "dPdx")
    ("vec2" "dPdy")))
  (("float" "textureProjGrad")
   (("sampler1DShadow" "sampler") ("vec4" "P") ("float" "dPdx")
    ("float" "dPdy")))
  (("float" "textureProjGrad")
   (("sampler2DShadow" "sampler") ("vec4" "P") ("vec2" "dPdx") ("vec2" "dPdy")))
  (("gvec4" "textureProjGradOffset")
   (("gsampler1D" "sampler") ("vec2" "P") ("float" "dPdx") ("float" "dPdy")
    ("int" "offset")))
  (("gvec4" "textureProjGradOffset")
   (("gsampler1D" "sampler") ("vec4" "P") ("float" "dPdx") ("float" "dPdy")
    ("int" "offset")))
  (("gvec4" "textureProjGradOffset")
   (("gsampler2D" "sampler") ("vec3" "P") ("vec2" "dPdx") ("vec2" "dPdy")
    ("vec2" "offset")))
  (("gvec4" "textureProjGradOffset")
   (("gsampler2D" "sampler") ("vec4" "P") ("vec2" "dPdx") ("vec2" "dPdy")
    ("vec2" "offset")))
  (("gvec4" "textureProjGradOffset")
   (("gsampler2DRect" "sampler") ("vec3" "P") ("vec2" "dPdx") ("vec2" "dPdy")
    ("ivec2" "offset")))
  (("gvec4" "textureProjGradOffset")
   (("gsampler2DRect" "sampler") ("vec4" "P") ("vec2" "dPdx") ("vec2" "dPdy")
    ("ivec2" "offset")))
  (("float" "textureProjGradOffset")
   (("sampler2DRectShadow" "sampler") ("vec4" "P") ("vec2" "dPdx")
    ("vec2" "dPdy") ("ivec2" "offset")))
  (("gvec4" "textureProjGradOffset")
   (("gsampler3D" "sampler") ("vec4" "P") ("vec3" "dPdx") ("vec3" "dPdy")
    ("vec3" "offset")))
  (("float" "textureProjGradOffset")
   (("sampler1DShadow" "sampler") ("vec4" "P") ("float" "dPdx") ("float" "dPdy")
    ("int" "offset")))
  (("float" "textureProjGradOffset")
   (("sampler2DShadow" "sampler") ("vec4" "P") ("vec2" "dPdx") ("vec2" "dPdy")
    ("vec2" "offset")))
  (("vec4" "texture1D")
   (("sampler1D" "sampler") ("float" "coord") (("float" "bias"))))
  (("vec4" "texture1DProj")
   (("sampler1D" "sampler") ("vec2" "coord") (("float" "bias"))))
  (("vec4" "texture1DProj")
   (("sampler1D" "sampler") ("vec4" "coord") (("float" "bias"))))
  (("vec4" "texture1DLod")
   (("sampler1D" "sampler") ("float" "coord") ("float" "lod")))
  (("vec4" "texture1DProjLod")
   (("sampler1D" "sampler") ("vec2" "coord") ("float" "lod")))
  (("vec4" "texture1DProjLod")
   (("sampler1D" "sampler") ("vec4" "coord") ("float" "lod")))
  (("vec4" "texture2D")
   (("sampler2D" "sampler") ("vec2" "coord") (("float" "bias"))))
  (("vec4" "texture2DProj")
   (("sampler2D" "sampler") ("vec3" "coord") (("float" "bias"))))
  (("vec4" "texture2DProj")
   (("sampler2D" "sampler") ("vec4" "coord") (("float" "bias"))))
  (("vec4" "texture2DLod")
   (("sampler2D" "sampler") ("vec2" "coord") ("float" "lod")))
  (("vec4" "texture2DProjLod")
   (("sampler2D" "sampler") ("vec3" "coord") ("float" "lod")))
  (("vec4" "texture2DProjLod")
   (("sampler2D" "sampler") ("vec4" "coord") ("float" "lod")))
  (("vec4" "texture3D")
   (("sampler3D" "sampler") ("vec3" "coord") (("float" "bias"))))
  (("vec4" "texture3DProj")
   (("sampler3D" "sampler") ("vec4" "coord") (("float" "bias"))))
  (("vec4" "texture3DLod")
   (("sampler3D" "sampler") ("vec3" "coord") ("float" "lod")))
  (("vec4" "texture3DProjLod")
   (("sampler3D" "sampler") ("vec4" "coord") ("float" "lod")))
  (("vec4" "textureCube")
   (("samplerCube" "sampler") ("vec3" "coord") (("float" "bias"))))
  (("vec4" "textureCubeLod")
   (("samplerCube" "sampler") ("vec3" "coord") ("float" "lod")))
  (("vec4" "shadow1D")
   (("sampler1DShadow" "sampler") ("vec3" "coord") (("float" "bias"))))
  (("vec4" "shadow2D")
   (("sampler2DShadow" "sampler") ("vec3" "coord") (("float" "bias"))))
  (("vec4" "shadow1DProj")
   (("sampler1DShadow" "sampler") ("vec4" "coord") (("float" "bias"))))
  (("vec4" "shadow2DProj")
   (("sampler2DShadow" "sampler") ("vec4" "coord") (("float" "bias"))))
  (("vec4" "shadow1DLod")
   (("sampler1DShadow" "sampler") ("vec3" "coord") ("float" "lod")))
  (("vec4" "shadow2DLod")
   (("sampler2DShadow" "sampler") ("vec3" "coord") ("float" "lod")))
  (("vec4" "shadow1DProjLod")
   (("sampler1DShadow" "sampler") ("vec4" "coord") ("float" "lod")))
  (("vec4" "shadow2DProjLod")
   (("sampler2DShadow" "sampler") ("vec4" "coord") ("float" "lod"))))

((("int" "textureSize") ("gsampler1D" "sampler") ("int" "lod"))
 (("ivec2" "textureSize") ("gsampler2D" "sampler") ("int" "lod"))
 (("ivec3" "textureSize") ("gsampler3D" "sampler") ("int" "lod"))
 (("ivec2" "textureSize") ("gsamplerCube" "sampler") ("int" "lod"))
 (("int" "textureSize") ("sampler1DShadow" "sampler") ("int" "lod"))
 (("ivec2" "textureSize") ("sampler2DShadow" "sampler") ("int" "lod"))
 (("ivec2" "textureSize") ("samplerCubeShadow" "sampler") ("int" "lod"))
 (("ivec2" "textureSize") ("gsampler2DRect" "sampler"))
 (("ivec2" "textureSize") ("sampler2DRectShadow" "sampler"))
 (("ivec2" "textureSize") ("gsampler1DArray" "sampler") ("int" "lod"))
 (("ivec3" "textureSize") ("gsampler2DArray" "sampler") ("int" "lod"))
 (("ivec2" "textureSize") ("sampler1DArrayShadow" "sampler") ("int" "lod"))
 (("ivec3" "textureSize") ("sampler2DArrayShadow" "sampler") ("int" "lod"))
 (("int" "textureSize") ("gsamplerBuffer" "sampler"))
 (("ivec2" "textureSize") ("gsampler2DMS" "sampler"))
 (("ivec2" "textureSize") ("gsampler2DMSArray" "sampler"))
 (("gvec4" "texture") ("gsampler1D" "sampler") ("float" "P") ("float" "bias"))
 (("gvec4" "texture") ("gsampler1D" "sampler") ("float" "P"))
 (("gvec4" "texture") ("gsampler2D" "sampler") ("vec2" "P") ("float" "bias"))
 (("gvec4" "texture") ("gsampler2D" "sampler") ("vec2" "P"))
 (("gvec4" "texture") ("gsampler3D" "sampler") ("vec3" "P") ("float" "bias"))
 (("gvec4" "texture") ("gsampler3D" "sampler") ("vec3" "P"))
 (("gvec4" "texture") ("gsamplerCube" "sampler") ("vec3" "P") ("float" "bias"))
 (("gvec4" "texture") ("gsamplerCube" "sampler") ("vec3" "P"))
 (("float" "texture") ("sampler1DShadow" "sampler") ("vec3" "P")
  ("float" "bias"))
 (("float" "texture") ("sampler1DShadow" "sampler") ("vec3" "P"))
 (("float" "texture") ("sampler2DShadow" "sampler") ("vec3" "P")
  ("float" "bias"))
 (("float" "texture") ("sampler2DShadow" "sampler") ("vec3" "P"))
 (("float" "texture") ("samplerCubeShadow" "sampler") ("vec4" "P")
  ("float" "bias"))
 (("float" "texture") ("samplerCubeShadow" "sampler") ("vec4" "P"))
 (("gvec4" "texture") ("gsampler1DArray" "sampler") ("vec2" "P")
  ("float" "bias"))
 (("gvec4" "texture") ("gsampler1DArray" "sampler") ("vec2" "P"))
 (("gvec4" "texture") ("gsampler2DArray" "sampler") ("vec3" "P")
  ("float" "bias"))
 (("gvec4" "texture") ("gsampler2DArray" "sampler") ("vec3" "P"))
 (("float" "texture") ("sampler1DArrayShadow" "sampler") ("vec3" "P")
  ("float" "bias"))
 (("float" "texture") ("sampler1DArrayShadow" "sampler") ("vec3" "P"))
 (("float" "texture") ("sampler2DArrayShadow" "sampler") ("vec4" "P"))
 (("gvec4" "texture") ("gsampler2DRect" "sampler") ("vec2" "P"))
 (("float" "texture") ("sampler2DRectShadow" "sampler") ("vec3" "P"))
 (("gvec4" "textureProj") ("gsampler1D" "sampler") ("vec2" "P")
  ("float" "bias"))
 (("gvec4" "textureProj") ("gsampler1D" "sampler") ("vec2" "P"))
 (("gvec4" "textureProj") ("gsampler1D" "sampler") ("vec4" "P")
  ("float" "bias"))
 (("gvec4" "textureProj") ("gsampler1D" "sampler") ("vec4" "P"))
 (("gvec4" "textureProj") ("gsampler2D" "sampler") ("vec3" "P")
  ("float" "bias"))
 (("gvec4" "textureProj") ("gsampler2D" "sampler") ("vec3" "P"))
 (("gvec4" "textureProj") ("gsampler2D" "sampler") ("vec4" "P")
  ("float" "bias"))
 (("gvec4" "textureProj") ("gsampler2D" "sampler") ("vec4" "P"))
 (("gvec4" "textureProj") ("gsampler3D" "sampler") ("vec4" "P")
  ("float" "bias"))
 (("gvec4" "textureProj") ("gsampler3D" "sampler") ("vec4" "P"))
 (("float" "textureProj") ("sampler1DShadow" "sampler") ("vec4" "P")
  ("float" "bias"))
 (("float" "textureProj") ("sampler1DShadow" "sampler") ("vec4" "P"))
 (("float" "textureProj") ("sampler2DShadow" "sampler") ("vec4" "P")
  ("float" "bias"))
 (("float" "textureProj") ("sampler2DShadow" "sampler") ("vec4" "P"))
 (("gvec4" "textureProj") ("gsampler2DRect" "sampler") ("vec3" "P"))
 (("gvec4" "textureProj") ("gsampler2DRect" "sampler") ("vec4" "P"))
 (("float" "textureProj") ("sampler2DRectShadow" "sampler") ("vec4" "P"))
 (("gvec4" "textureLod") ("gsampler1D" "sampler") ("float" "P")
  ("float" "lod"))
 (("gvec4" "textureLod") ("gsampler2D" "sampler") ("vec2" "P") ("float" "lod"))
 (("gvec4" "textureLod") ("gsampler3D" "sampler") ("vec3" "P") ("float" "lod"))
 (("gvec4" "textureLod") ("gsamplerCube" "sampler") ("vec3" "P")
  ("float" "lod"))
 (("float" "textureLod") ("sampler1DShadow" "sampler") ("vec3" "P")
  ("float" "lod"))
 (("float" "textureLod") ("sampler2DShadow" "sampler") ("vec3" "P")
  ("float" "lod"))
 (("gvec4" "textureLod") ("gsampler1DArray" "sampler") ("vec2" "P")
  ("float" "lod"))
 (("gvec4" "textureLod") ("gsampler2DArray" "sampler") ("vec3" "P")
  ("float" "lod"))
 (("float" "textureLod") ("sampler1DArrayShadow" "sampler") ("vec3" "P")
  ("float" "lod"))
 (("gvec4" "textureOffset") ("gsampler1D" "sampler") ("float" "P")
  ("int" "offset") ("float" "bias"))
 (("gvec4" "textureOffset") ("gsampler1D" "sampler") ("float" "P")
  ("int" "offset"))
 (("gvec4" "textureOffset") ("gsampler2D" "sampler") ("vec2" "P")
  ("ivec2" "offset") ("float" "bias"))
 (("gvec4" "textureOffset") ("gsampler2D" "sampler") ("vec2" "P")
  ("ivec2" "offset"))
 (("gvec4" "textureOffset") ("gsampler3D" "sampler") ("vec3" "P")
  ("ivec3" "offset") ("float" "bias"))
 (("gvec4" "textureOffset") ("gsampler3D" "sampler") ("vec3" "P")
  ("ivec3" "offset"))
 (("gvec4" "textureOffset") ("gsampler2DRect" "sampler") ("vec2" "P")
  ("ivec2" "offset"))
 (("float" "textureOffset") ("sampler2DRectShadow" "sampler") ("vec3" "P")
  ("ivec2" "offset"))
 (("float" "textureOffset") ("sampler1DShadow" "sampler") ("vec3" "P")
  ("int" "offset") ("float" "bias"))
 (("float" "textureOffset") ("sampler1DShadow" "sampler") ("vec3" "P")
  ("int" "offset"))
 (("float" "textureOffset") ("sampler2DShadow" "sampler") ("vec3" "P")
  ("ivec2" "offset") ("float" "bias"))
 (("float" "textureOffset") ("sampler2DShadow" "sampler") ("vec3" "P")
  ("ivec2" "offset"))
 (("gvec4" "textureOffset") ("gsampler1DArray" "sampler") ("vec2" "P")
  ("int" "offset") ("float" "bias"))
 (("gvec4" "textureOffset") ("gsampler1DArray" "sampler") ("vec2" "P")
  ("int" "offset"))
 (("gvec4" "textureOffset") ("gsampler2DArray" "sampler") ("vec3" "P")
  ("ivec2" "offset") ("float" "bias"))
 (("gvec4" "textureOffset") ("gsampler2DArray" "sampler") ("vec3" "P")
  ("ivec2" "offset"))
 (("float" "textureOffset") ("sampler1DArrayShadow" "sampler") ("vec3" "P")
  ("int" "offset") ("float" "bias"))
 (("float" "textureOffset") ("sampler1DArrayShadow" "sampler") ("vec3" "P")
  ("int" "offset"))
 (("gvec4" "texelFetch") ("gsampler1D" "sampler") ("int" "P") ("int" "lod"))
 (("gvec4" "texelFetch") ("gsampler2D" "sampler") ("ivec2" "P") ("int" "lod"))
 (("gvec4" "texelFetch") ("gsampler3D" "sampler") ("ivec3" "P") ("int" "lod"))
 (("gvec4" "texelFetch") ("gsampler2DRect" "sampler") ("ivec2" "P"))
 (("gvec4" "texelFetch") ("gsampler1DArray" "sampler") ("ivec2" "P")
  ("int" "lod"))
 (("gvec4" "texelFetch") ("gsampler2DArray" "sampler") ("ivec3" "P")
  ("int" "lod"))
 (("gvec4" "texelFetch") ("gsamplerBuffer" "sampler") ("int" "P"))
 (("gvec4" "texelFetch") ("gsampler2DMS" "sampler") ("ivec2" "P")
  ("int" "sample"))
 (("gvec4" "texelFetch") ("gsampler2DMSArray" "sampler") ("ivec3" "P")
  ("int" "sample"))
 (("gvec4" "texelFetchOffset") ("gsampler1D" "sampler") ("int" "P")
  ("int" "lod") ("int" "offset"))
 (("gvec4" "texelFetchOffset") ("gsampler2D" "sampler") ("ivec2" "P")
  ("int" "lod") ("ivec2" "offset"))
 (("gvec4" "texelFetchOffset") ("gsampler3D" "sampler") ("ivec3" "P")
  ("int" "lod") ("ivec3" "offset"))
 (("gvec4" "texelFetchOffset") ("gsampler2DRect" "sampler") ("ivec2" "P")
  ("ivec2" "offset"))
 (("gvec4" "texelFetchOffset") ("gsampler1DArray" "sampler") ("ivec2" "P")
  ("int" "lod") ("int" "offset"))
 (("gvec4" "texelFetchOffset") ("gsampler2DArray" "sampler") ("ivec3" "P")
  ("int" "lod") ("ivec2" "offset"))
 (("gvec4" "textureProjOffset") ("gsampler1D" "sampler") ("vec2" "P")
  ("int" "offset") ("float" "bias"))
 (("gvec4" "textureProjOffset") ("gsampler1D" "sampler") ("vec2" "P")
  ("int" "offset"))
 (("gvec4" "textureProjOffset") ("gsampler1D" "sampler") ("vec4" "P")
  ("int" "offset") ("float" "bias"))
 (("gvec4" "textureProjOffset") ("gsampler1D" "sampler") ("vec4" "P")
  ("int" "offset"))
 (("gvec4" "textureProjOffset") ("gsampler2D" "sampler") ("vec3" "P")
  ("ivec2" "offset") ("float" "bias"))
 (("gvec4" "textureProjOffset") ("gsampler2D" "sampler") ("vec3" "P")
  ("ivec2" "offset"))
 (("gvec4" "textureProjOffset") ("gsampler2D" "sampler") ("vec4" "P")
  ("ivec2" "offset") ("float" "bias"))
 (("gvec4" "textureProjOffset") ("gsampler2D" "sampler") ("vec4" "P")
  ("ivec2" "offset"))
 (("gvec4" "textureProjOffset") ("gsampler3D" "sampler") ("vec4" "P")
  ("ivec3" "offset") ("float" "bias"))
 (("gvec4" "textureProjOffset") ("gsampler3D" "sampler") ("vec4" "P")
  ("ivec3" "offset"))
 (("gvec4" "textureProjOffset") ("gsampler2DRect" "sampler") ("vec3" "P")
  ("ivec2" "offset"))
 (("gvec4" "textureProjOffset") ("gsampler2DRect" "sampler") ("vec4" "P")
  ("ivec2" "offset"))
 (("float" "textureProjOffset") ("sampler2DRectShadow" "sampler") ("vec4" "P")
  ("ivec2" "offset"))
 (("float" "textureProjOffset") ("sampler1DShadow" "sampler") ("vec4" "P")
  ("int" "offset") ("float" "bias"))
 (("float" "textureProjOffset") ("sampler1DShadow" "sampler") ("vec4" "P")
  ("int" "offset"))
 (("float" "textureProjOffset") ("sampler2DShadow" "sampler") ("vec4" "P")
  ("ivec2" "offset") ("float" "bias"))
 (("float" "textureProjOffset") ("sampler2DShadow" "sampler") ("vec4" "P")
  ("ivec2" "offset"))
 (("gvec4" "textureLodOffset") ("gsampler1D" "sampler") ("float" "P")
  ("float" "lod") ("int" "offset"))
 (("gvec4" "textureLodOffset") ("gsampler2D" "sampler") ("vec2" "P")
  ("float" "lod") ("ivec2" "offset"))
 (("gvec4" "textureLodOffset") ("gsampler3D" "sampler") ("vec3" "P")
  ("float" "lod") ("ivec3" "offset"))
 (("float" "textureLodOffset") ("sampler1DShadow" "sampler") ("vec3" "P")
  ("float" "lod") ("int" "offset"))
 (("float" "textureLodOffset") ("sampler2DShadow" "sampler") ("vec3" "P")
  ("float" "lod") ("ivec2" "offset"))
 (("gvec4" "textureLodOffset") ("gsampler1DArray" "sampler") ("vec2" "P")
  ("float" "lod") ("int" "offset"))
 (("gvec4" "textureLodOffset") ("gsampler2DArray" "sampler") ("vec3" "P")
  ("float" "lod") ("ivec2" "offset"))
 (("float" "textureLodOffset") ("sampler1DArrayShadow" "sampler") ("vec3" "P")
  ("float" "lod") ("int" "offset"))
 (("gvec4" "textureProjLod") ("gsampler1D" "sampler") ("vec2" "P")
  ("float" "lod"))
 (("gvec4" "textureProjLod") ("gsampler1D" "sampler") ("vec4" "P")
  ("float" "lod"))
 (("gvec4" "textureProjLod") ("gsampler2D" "sampler") ("vec3" "P")
  ("float" "lod"))
 (("gvec4" "textureProjLod") ("gsampler2D" "sampler") ("vec4" "P")
  ("float" "lod"))
 (("gvec4" "textureProjLod") ("gsampler3D" "sampler") ("vec4" "P")
  ("float" "lod"))
 (("float" "textureProjLod") ("sampler1DShadow" "sampler") ("vec4" "P")
  ("float" "lod"))
 (("float" "textureProjLod") ("sampler2DShadow" "sampler") ("vec4" "P")
  ("float" "lod"))
 (("gvec4" "textureProjLodOffset") ("gsampler1D" "sampler") ("vec2" "P")
  ("float" "lod") ("int" "offset"))
 (("gvec4" "textureProjLodOffset") ("gsampler1D" "sampler") ("vec4" "P")
  ("float" "lod") ("int" "offset"))
 (("gvec4" "textureProjLodOffset") ("gsampler2D" "sampler") ("vec3" "P")
  ("float" "lod") ("ivec2" "offset"))
 (("gvec4" "textureProjLodOffset") ("gsampler2D" "sampler") ("vec4" "P")
  ("float" "lod") ("ivec2" "offset"))
 (("gvec4" "textureProjLodOffset") ("gsampler3D" "sampler") ("vec4" "P")
  ("float" "lod") ("ivec3" "offset"))
 (("float" "textureProjLodOffset") ("sampler1DShadow" "sampler") ("vec4" "P")
  ("float" "lod") ("int" "offset"))
 (("float" "textureProjLodOffset") ("sampler2DShadow" "sampler") ("vec4" "P")
  ("float" "lod") ("ivec2" "offset"))
 (("gvec4" "textureGrad") ("gsampler1D" "sampler") ("float" "P")
  ("float" "dPdx") ("float" "dPdy"))
 (("gvec4" "textureGrad") ("gsampler2D" "sampler") ("vec2" "P") ("vec2" "dPdx")
  ("vec2" "dPdy"))
 (("gvec4" "textureGrad") ("gsampler3D" "sampler") ("vec3" "P") ("vec3" "dPdx")
  ("vec3" "dPdy"))
 (("gvec4" "textureGrad") ("gsamplerCube" "sampler") ("vec3" "P")
  ("vec3" "dPdx") ("vec3" "dPdy"))
 (("gvec4" "textureGrad") ("gsampler2DRect" "sampler") ("vec2" "P")
  ("vec2" "dPdx") ("vec2" "dPdy"))
 (("float" "textureGrad") ("sampler2DRectShadow" "sampler") ("vec3" "P")
  ("vec2" "dPdx") ("vec2" "dPdy"))
 (("float" "textureGrad") ("sampler1DShadow" "sampler") ("vec3" "P")
  ("float" "dPdx") ("float" "dPdy"))
 (("float" "textureGrad") ("sampler2DShadow" "sampler") ("vec3" "P")
  ("vec2" "dPdx") ("vec2" "dPdy"))
 (("float" "textureGrad") ("samplerCubeShadow" "sampler") ("vec4" "P")
  ("vec3" "dPdx") ("vec3" "dPdy"))
 (("gvec4" "textureGrad") ("gsampler1DArray" "sampler") ("vec2" "P")
  ("float" "dPdx") ("float" "dPdy"))
 (("gvec4" "textureGrad") ("gsampler2DArray" "sampler") ("vec3" "P")
  ("vec2" "dPdx") ("vec2" "dPdy"))
 (("float" "textureGrad") ("sampler1DArrayShadow" "sampler") ("vec3" "P")
  ("float" "dPdx") ("float" "dPdy"))
 (("float" "textureGrad") ("sampler2DArrayShadow" "sampler") ("vec4" "P")
  ("vec2" "dPdx") ("vec2" "dPdy"))
 (("gvec4" "textureGradOffset") ("gsampler1D" "sampler") ("float" "P")
  ("float" "dPdx") ("float" "dPdy") ("int" "offset"))
 (("gvec4" "textureGradOffset") ("gsampler2D" "sampler") ("vec2" "P")
  ("vec2" "dPdx") ("vec2" "dPdy") ("ivec2" "offset"))
 (("gvec4" "textureGradOffset") ("gsampler3D" "sampler") ("vec3" "P")
  ("vec3" "dPdx") ("vec3" "dPdy") ("ivec3" "offset"))
 (("gvec4" "textureGradOffset") ("gsampler2DRect" "sampler") ("vec2" "P")
  ("vec2" "dPdx") ("vec2" "dPdy") ("ivec2" "offset"))
 (("float" "textureGradOffset") ("sampler2DRectShadow" "sampler") ("vec3" "P")
  ("vec2" "dPdx") ("vec2" "dPdy") ("ivec2" "offset"))
 (("float" "textureGradOffset") ("sampler1DShadow" "sampler") ("vec3" "P")
  ("float" "dPdx") ("float" "dPdy") ("int" "offset"))
 (("float" "textureGradOffset") ("sampler2DShadow" "sampler") ("vec3" "P")
  ("vec2" "dPdx") ("vec2" "dPdy") ("ivec2" "offset"))
 (("gvec4" "textureGradOffset") ("gsampler1DArray" "sampler") ("vec2" "P")
  ("float" "dPdx") ("float" "dPdy") ("int" "offset"))
 (("gvec4" "textureGradOffset") ("gsampler2DArray" "sampler") ("vec3" "P")
  ("vec2" "dPdx") ("vec2" "dPdy") ("ivec2" "offset"))
 (("float" "textureGradOffset") ("sampler1DArrayShadow" "sampler") ("vec3" "P")
  ("float" "dPdx") ("float" "dPdy") ("int" "offset"))
 (("float" "textureGradOffset") ("sampler2DArrayShadow" "sampler") ("vec4" "P")
  ("vec2" "dPdx") ("vec2" "dPdy") ("ivec2" "offset"))
 (("gvec4" "textureProjGrad") ("gsampler1D" "sampler") ("vec2" "P")
  ("float" "dPdx") ("float" "dPdy"))
 (("gvec4" "textureProjGrad") ("gsampler1D" "sampler") ("vec4" "P")
  ("float" "dPdx") ("float" "dPdy"))
 (("gvec4" "textureProjGrad") ("gsampler2D" "sampler") ("vec3" "P")
  ("vec2" "dPdx") ("vec2" "dPdy"))
 (("gvec4" "textureProjGrad") ("gsampler2D" "sampler") ("vec4" "P")
  ("vec2" "dPdx") ("vec2" "dPdy"))
 (("gvec4" "textureProjGrad") ("gsampler3D" "sampler") ("vec4" "P")
  ("vec3" "dPdx") ("vec3" "dPdy"))
 (("gvec4" "textureProjGrad") ("gsampler2DRect" "sampler") ("vec3" "P")
  ("vec2" "dPdx") ("vec2" "dPdy"))
 (("gvec4" "textureProjGrad") ("gsampler2DRect" "sampler") ("vec4" "P")
  ("vec2" "dPdx") ("vec2" "dPdy"))
 (("float" "textureProjGrad") ("sampler2DRectShadow" "sampler") ("vec4" "P")
  ("vec2" "dPdx") ("vec2" "dPdy"))
 (("float" "textureProjGrad") ("sampler1DShadow" "sampler") ("vec4" "P")
  ("float" "dPdx") ("float" "dPdy"))
 (("float" "textureProjGrad") ("sampler2DShadow" "sampler") ("vec4" "P")
  ("vec2" "dPdx") ("vec2" "dPdy"))
 (("gvec4" "textureProjGradOffset") ("gsampler1D" "sampler") ("vec2" "P")
  ("float" "dPdx") ("float" "dPdy") ("int" "offset"))
 (("gvec4" "textureProjGradOffset") ("gsampler1D" "sampler") ("vec4" "P")
  ("float" "dPdx") ("float" "dPdy") ("int" "offset"))
 (("gvec4" "textureProjGradOffset") ("gsampler2D" "sampler") ("vec3" "P")
  ("vec2" "dPdx") ("vec2" "dPdy") ("vec2" "offset"))
 (("gvec4" "textureProjGradOffset") ("gsampler2D" "sampler") ("vec4" "P")
  ("vec2" "dPdx") ("vec2" "dPdy") ("vec2" "offset"))
 (("gvec4" "textureProjGradOffset") ("gsampler2DRect" "sampler") ("vec3" "P")
  ("vec2" "dPdx") ("vec2" "dPdy") ("ivec2" "offset"))
 (("gvec4" "textureProjGradOffset") ("gsampler2DRect" "sampler") ("vec4" "P")
  ("vec2" "dPdx") ("vec2" "dPdy") ("ivec2" "offset"))
 (("float" "textureProjGradOffset") ("sampler2DRectShadow" "sampler")
  ("vec4" "P") ("vec2" "dPdx") ("vec2" "dPdy") ("ivec2" "offset"))
 (("gvec4" "textureProjGradOffset") ("gsampler3D" "sampler") ("vec4" "P")
  ("vec3" "dPdx") ("vec3" "dPdy") ("vec3" "offset"))
 (("float" "textureProjGradOffset") ("sampler1DShadow" "sampler") ("vec4" "P")
  ("float" "dPdx") ("float" "dPdy") ("int" "offset"))
 (("float" "textureProjGradOffset") ("sampler2DShadow" "sampler") ("vec4" "P")
  ("vec2" "dPdx") ("vec2" "dPdy") ("vec2" "offset"))
 (("vec4" "texture1D") ("sampler1D" "sampler") ("float" "coord")
  ("float" "bias"))
 (("vec4" "texture1D") ("sampler1D" "sampler") ("float" "coord"))
 (("vec4" "texture1DProj") ("sampler1D" "sampler") ("vec2" "coord")
  ("float" "bias"))
 (("vec4" "texture1DProj") ("sampler1D" "sampler") ("vec2" "coord"))
 (("vec4" "texture1DProj") ("sampler1D" "sampler") ("vec4" "coord")
  ("float" "bias"))
 (("vec4" "texture1DProj") ("sampler1D" "sampler") ("vec4" "coord"))
 (("vec4" "texture1DLod") ("sampler1D" "sampler") ("float" "coord")
  ("float" "lod"))
 (("vec4" "texture1DProjLod") ("sampler1D" "sampler") ("vec2" "coord")
  ("float" "lod"))
 (("vec4" "texture1DProjLod") ("sampler1D" "sampler") ("vec4" "coord")
  ("float" "lod"))
 (("vec4" "texture2D") ("sampler2D" "sampler") ("vec2" "coord")
  ("float" "bias"))
 (("vec4" "texture2D") ("sampler2D" "sampler") ("vec2" "coord"))
 (("vec4" "texture2DProj") ("sampler2D" "sampler") ("vec3" "coord")
  ("float" "bias"))
 (("vec4" "texture2DProj") ("sampler2D" "sampler") ("vec3" "coord"))
 (("vec4" "texture2DProj") ("sampler2D" "sampler") ("vec4" "coord")
  ("float" "bias"))
 (("vec4" "texture2DProj") ("sampler2D" "sampler") ("vec4" "coord"))
 (("vec4" "texture2DLod") ("sampler2D" "sampler") ("vec2" "coord")
  ("float" "lod"))
 (("vec4" "texture2DProjLod") ("sampler2D" "sampler") ("vec3" "coord")
  ("float" "lod"))
 (("vec4" "texture2DProjLod") ("sampler2D" "sampler") ("vec4" "coord")
  ("float" "lod"))
 (("vec4" "texture3D") ("sampler3D" "sampler") ("vec3" "coord")
  ("float" "bias"))
 (("vec4" "texture3D") ("sampler3D" "sampler") ("vec3" "coord"))
 (("vec4" "texture3DProj") ("sampler3D" "sampler") ("vec4" "coord")
  ("float" "bias"))
 (("vec4" "texture3DProj") ("sampler3D" "sampler") ("vec4" "coord"))
 (("vec4" "texture3DLod") ("sampler3D" "sampler") ("vec3" "coord")
  ("float" "lod"))
 (("vec4" "texture3DProjLod") ("sampler3D" "sampler") ("vec4" "coord")
  ("float" "lod"))
 (("vec4" "textureCube") ("samplerCube" "sampler") ("vec3" "coord")
  ("float" "bias"))
 (("vec4" "textureCube") ("samplerCube" "sampler") ("vec3" "coord"))
 (("vec4" "textureCubeLod") ("samplerCube" "sampler") ("vec3" "coord")
  ("float" "lod"))
 (("vec4" "shadow1D") ("sampler1DShadow" "sampler") ("vec3" "coord")
  ("float" "bias"))
 (("vec4" "shadow1D") ("sampler1DShadow" "sampler") ("vec3" "coord"))
 (("vec4" "shadow2D") ("sampler2DShadow" "sampler") ("vec3" "coord")
  ("float" "bias"))
 (("vec4" "shadow2D") ("sampler2DShadow" "sampler") ("vec3" "coord"))
 (("vec4" "shadow1DProj") ("sampler1DShadow" "sampler") ("vec4" "coord")
  ("float" "bias"))
 (("vec4" "shadow1DProj") ("sampler1DShadow" "sampler") ("vec4" "coord"))
 (("vec4" "shadow2DProj") ("sampler2DShadow" "sampler") ("vec4" "coord")
  ("float" "bias"))
 (("vec4" "shadow2DProj") ("sampler2DShadow" "sampler") ("vec4" "coord"))
 (("vec4" "shadow1DLod") ("sampler1DShadow" "sampler") ("vec3" "coord")
  ("float" "lod"))
 (("vec4" "shadow2DLod") ("sampler2DShadow" "sampler") ("vec3" "coord")
  ("float" "lod"))
 (("vec4" "shadow1DProjLod") ("sampler1DShadow" "sampler") ("vec4" "coord")
  ("float" "lod"))
 (("vec4" "shadow2DProjLod") ("sampler2DShadow" "sampler") ("vec4" "coord")
  ("float" "lod")))

(((:int "textureSize") (:sampler1D "sampler") (:int "lod"))
 ((:int "textureSize") (:isampler1D "sampler") (:int "lod"))
 ((:int "textureSize") (:usampler1D "sampler") (:int "lod"))
 ((:ivec2 "textureSize") (:sampler2D "sampler") (:int "lod"))
 ((:ivec2 "textureSize") (:isampler2D "sampler") (:int "lod"))
 ((:ivec2 "textureSize") (:usampler2D "sampler") (:int "lod"))
 ((:ivec3 "textureSize") (:sampler3D "sampler") (:int "lod"))
 ((:ivec3 "textureSize") (:isampler3D "sampler") (:int "lod"))
 ((:ivec3 "textureSize") (:usampler3D "sampler") (:int "lod"))
 ((:ivec2 "textureSize") (:samplerCube "sampler") (:int "lod"))
 ((:ivec2 "textureSize") (:isamplerCube "sampler") (:int "lod"))
 ((:ivec2 "textureSize") (:usamplerCube "sampler") (:int "lod"))
 ((:ivec2 "textureSize") (:sampler2DRect "sampler"))
 ((:ivec2 "textureSize") (:isampler2DRect "sampler"))
 ((:ivec2 "textureSize") (:usampler2DRect "sampler"))
 ((:ivec2 "textureSize") (:sampler1DArray "sampler") (:int "lod"))
 ((:ivec2 "textureSize") (:isampler1DArray "sampler") (:int "lod"))
 ((:ivec2 "textureSize") (:usampler1DArray "sampler") (:int "lod"))
 ((:ivec3 "textureSize") (:sampler2DArray "sampler") (:int "lod"))
 ((:ivec3 "textureSize") (:isampler2DArray "sampler") (:int "lod"))
 ((:ivec3 "textureSize") (:usampler2DArray "sampler") (:int "lod"))
 ((:int "textureSize") (:samplerBuffer "sampler"))
 ((:int "textureSize") (:isamplerBuffer "sampler"))
 ((:int "textureSize") (:usamplerBuffer "sampler"))
 ((:ivec2 "textureSize") (:sampler2DMS "sampler"))
 ((:ivec2 "textureSize") (:isampler2DMS "sampler"))
 ((:ivec2 "textureSize") (:usampler2DMS "sampler"))
 ((:ivec2 "textureSize") (:sampler2DMSArray "sampler"))
 ((:ivec2 "textureSize") (:isampler2DMSArray "sampler"))
 ((:ivec2 "textureSize") (:usampler2DMSArray "sampler"))
 ((:vec4 "texture") (:sampler1D "sampler") (:float "P")
  (:float "bias"))
 ((:ivec4 "texture") (:isampler1D "sampler") (:float "P")
  (:float "bias"))
 ((:uvec4 "texture") (:usampler1D "sampler") (:float "P")
  (:float "bias"))
 ((:vec4 "texture") (:sampler1D "sampler") (:float "P"))
 ((:ivec4 "texture") (:isampler1D "sampler") (:float "P"))
 ((:uvec4 "texture") (:usampler1D "sampler") (:float "P"))
 ((:vec4 "texture") (:sampler2D "sampler") (:vec2 "P") (:float "bias"))
 ((:ivec4 "texture") (:isampler2D "sampler") (:vec2 "P")
  (:float "bias"))
 ((:uvec4 "texture") (:usampler2D "sampler") (:vec2 "P")
  (:float "bias"))
 ((:vec4 "texture") (:sampler2D "sampler") (:vec2 "P"))
 ((:ivec4 "texture") (:isampler2D "sampler") (:vec2 "P"))
 ((:uvec4 "texture") (:usampler2D "sampler") (:vec2 "P"))
 ((:vec4 "texture") (:sampler3D "sampler") (:vec3 "P") (:float "bias"))
 ((:ivec4 "texture") (:isampler3D "sampler") (:vec3 "P")
  (:float "bias"))
 ((:uvec4 "texture") (:usampler3D "sampler") (:vec3 "P")
  (:float "bias"))
 ((:vec4 "texture") (:sampler3D "sampler") (:vec3 "P"))
 ((:ivec4 "texture") (:isampler3D "sampler") (:vec3 "P"))
 ((:uvec4 "texture") (:usampler3D "sampler") (:vec3 "P"))
 ((:vec4 "texture") (:samplerCube "sampler") (:vec3 "P")
  (:float "bias"))
 ((:ivec4 "texture") (:isamplerCube "sampler") (:vec3 "P")
  (:float "bias"))
 ((:uvec4 "texture") (:usamplerCube "sampler") (:vec3 "P")
  (:float "bias"))
 ((:vec4 "texture") (:samplerCube "sampler") (:vec3 "P"))
 ((:ivec4 "texture") (:isamplerCube "sampler") (:vec3 "P"))
 ((:uvec4 "texture") (:usamplerCube "sampler") (:vec3 "P"))
 ((:vec4 "texture") (:sampler1DArray "sampler") (:vec2 "P")
  (:float "bias"))
 ((:ivec4 "texture") (:isampler1DArray "sampler") (:vec2 "P")
  (:float "bias"))
 ((:uvec4 "texture") (:usampler1DArray "sampler") (:vec2 "P")
  (:float "bias"))
 ((:vec4 "texture") (:sampler1DArray "sampler") (:vec2 "P"))
 ((:ivec4 "texture") (:isampler1DArray "sampler") (:vec2 "P"))
 ((:uvec4 "texture") (:usampler1DArray "sampler") (:vec2 "P"))
 ((:vec4 "texture") (:sampler2DArray "sampler") (:vec3 "P")
  (:float "bias"))
 ((:ivec4 "texture") (:isampler2DArray "sampler") (:vec3 "P")
  (:float "bias"))
 ((:uvec4 "texture") (:usampler2DArray "sampler") (:vec3 "P")
  (:float "bias"))
 ((:vec4 "texture") (:sampler2DArray "sampler") (:vec3 "P"))
 ((:ivec4 "texture") (:isampler2DArray "sampler") (:vec3 "P"))
 ((:uvec4 "texture") (:usampler2DArray "sampler") (:vec3 "P"))
 ((:vec4 "texture") (:sampler2DRect "sampler") (:vec2 "P"))
 ((:ivec4 "texture") (:isampler2DRect "sampler") (:vec2 "P"))
 ((:uvec4 "texture") (:usampler2DRect "sampler") (:vec2 "P"))
 ((:vec4 "textureProj") (:sampler1D "sampler") (:vec2 "P")
  (:float "bias"))
 ((:ivec4 "textureProj") (:isampler1D "sampler") (:vec2 "P")
  (:float "bias"))
 ((:uvec4 "textureProj") (:usampler1D "sampler") (:vec2 "P")
  (:float "bias"))
 ((:vec4 "textureProj") (:sampler1D "sampler") (:vec2 "P"))
 ((:ivec4 "textureProj") (:isampler1D "sampler") (:vec2 "P"))
 ((:uvec4 "textureProj") (:usampler1D "sampler") (:vec2 "P"))
 ((:vec4 "textureProj") (:sampler1D "sampler") (:vec4 "P")
  (:float "bias"))
 ((:ivec4 "textureProj") (:isampler1D "sampler") (:vec4 "P")
  (:float "bias"))
 ((:uvec4 "textureProj") (:usampler1D "sampler") (:vec4 "P")
  (:float "bias"))
 ((:vec4 "textureProj") (:sampler1D "sampler") (:vec4 "P"))
 ((:ivec4 "textureProj") (:isampler1D "sampler") (:vec4 "P"))
 ((:uvec4 "textureProj") (:usampler1D "sampler") (:vec4 "P"))
 ((:vec4 "textureProj") (:sampler2D "sampler") (:vec3 "P")
  (:float "bias"))
 ((:ivec4 "textureProj") (:isampler2D "sampler") (:vec3 "P")
  (:float "bias"))
 ((:uvec4 "textureProj") (:usampler2D "sampler") (:vec3 "P")
  (:float "bias"))
 ((:vec4 "textureProj") (:sampler2D "sampler") (:vec3 "P"))
 ((:ivec4 "textureProj") (:isampler2D "sampler") (:vec3 "P"))
 ((:uvec4 "textureProj") (:usampler2D "sampler") (:vec3 "P"))
 ((:vec4 "textureProj") (:sampler2D "sampler") (:vec4 "P")
  (:float "bias"))
 ((:ivec4 "textureProj") (:isampler2D "sampler") (:vec4 "P")
  (:float "bias"))
 ((:uvec4 "textureProj") (:usampler2D "sampler") (:vec4 "P")
  (:float "bias"))
 ((:vec4 "textureProj") (:sampler2D "sampler") (:vec4 "P"))
 ((:ivec4 "textureProj") (:isampler2D "sampler") (:vec4 "P"))
 ((:uvec4 "textureProj") (:usampler2D "sampler") (:vec4 "P"))
 ((:vec4 "textureProj") (:sampler3D "sampler") (:vec4 "P")
  (:float "bias"))
 ((:ivec4 "textureProj") (:isampler3D "sampler") (:vec4 "P")
  (:float "bias"))
 ((:uvec4 "textureProj") (:usampler3D "sampler") (:vec4 "P")
  (:float "bias"))
 ((:vec4 "textureProj") (:sampler3D "sampler") (:vec4 "P"))
 ((:ivec4 "textureProj") (:isampler3D "sampler") (:vec4 "P"))
 ((:uvec4 "textureProj") (:usampler3D "sampler") (:vec4 "P"))
 ((:vec4 "textureProj") (:sampler2DRect "sampler") (:vec3 "P"))
 ((:ivec4 "textureProj") (:isampler2DRect "sampler") (:vec3 "P"))
 ((:uvec4 "textureProj") (:usampler2DRect "sampler") (:vec3 "P"))
 ((:vec4 "textureProj") (:sampler2DRect "sampler") (:vec4 "P"))
 ((:ivec4 "textureProj") (:isampler2DRect "sampler") (:vec4 "P"))
 ((:uvec4 "textureProj") (:usampler2DRect "sampler") (:vec4 "P"))
 ((:vec4 "textureLod") (:sampler1D "sampler") (:float "P")
  (:float "lod"))
 ((:ivec4 "textureLod") (:isampler1D "sampler") (:float "P")
  (:float "lod"))
 ((:uvec4 "textureLod") (:usampler1D "sampler") (:float "P")
  (:float "lod"))
 ((:vec4 "textureLod") (:sampler2D "sampler") (:vec2 "P")
  (:float "lod"))
 ((:ivec4 "textureLod") (:isampler2D "sampler") (:vec2 "P")
  (:float "lod"))
 ((:uvec4 "textureLod") (:usampler2D "sampler") (:vec2 "P")
  (:float "lod"))
 ((:vec4 "textureLod") (:sampler3D "sampler") (:vec3 "P")
  (:float "lod"))
 ((:ivec4 "textureLod") (:isampler3D "sampler") (:vec3 "P")
  (:float "lod"))
 ((:uvec4 "textureLod") (:usampler3D "sampler") (:vec3 "P")
  (:float "lod"))
 ((:vec4 "textureLod") (:samplerCube "sampler") (:vec3 "P")
  (:float "lod"))
 ((:ivec4 "textureLod") (:isamplerCube "sampler") (:vec3 "P")
  (:float "lod"))
 ((:uvec4 "textureLod") (:usamplerCube "sampler") (:vec3 "P")
  (:float "lod"))
 ((:vec4 "textureLod") (:sampler1DArray "sampler") (:vec2 "P")
  (:float "lod"))
 ((:ivec4 "textureLod") (:isampler1DArray "sampler") (:vec2 "P")
  (:float "lod"))
 ((:uvec4 "textureLod") (:usampler1DArray "sampler") (:vec2 "P")
  (:float "lod"))
 ((:vec4 "textureLod") (:sampler2DArray "sampler") (:vec3 "P")
  (:float "lod"))
 ((:ivec4 "textureLod") (:isampler2DArray "sampler") (:vec3 "P")
  (:float "lod"))
 ((:uvec4 "textureLod") (:usampler2DArray "sampler") (:vec3 "P")
  (:float "lod"))
 ((:vec4 "textureOffset") (:sampler1D "sampler") (:float "P")
  (:int "offset") (:float "bias"))
 ((:ivec4 "textureOffset") (:isampler1D "sampler") (:float "P")
  (:int "offset") (:float "bias"))
 ((:uvec4 "textureOffset") (:usampler1D "sampler") (:float "P")
  (:int "offset") (:float "bias"))
 ((:vec4 "textureOffset") (:sampler1D "sampler") (:float "P")
  (:int "offset"))
 ((:ivec4 "textureOffset") (:isampler1D "sampler") (:float "P")
  (:int "offset"))
 ((:uvec4 "textureOffset") (:usampler1D "sampler") (:float "P")
  (:int "offset"))
 ((:vec4 "textureOffset") (:sampler2D "sampler") (:vec2 "P")
  (:ivec2 "offset") (:float "bias"))
 ((:ivec4 "textureOffset") (:isampler2D "sampler") (:vec2 "P")
  (:ivec2 "offset") (:float "bias"))
 ((:uvec4 "textureOffset") (:usampler2D "sampler") (:vec2 "P")
  (:ivec2 "offset") (:float "bias"))
 ((:vec4 "textureOffset") (:sampler2D "sampler") (:vec2 "P")
  (:ivec2 "offset"))
 ((:ivec4 "textureOffset") (:isampler2D "sampler") (:vec2 "P")
  (:ivec2 "offset"))
 ((:uvec4 "textureOffset") (:usampler2D "sampler") (:vec2 "P")
  (:ivec2 "offset"))
 ((:vec4 "textureOffset") (:sampler3D "sampler") (:vec3 "P")
  (:ivec3 "offset") (:float "bias"))
 ((:ivec4 "textureOffset") (:isampler3D "sampler") (:vec3 "P")
  (:ivec3 "offset") (:float "bias"))
 ((:uvec4 "textureOffset") (:usampler3D "sampler") (:vec3 "P")
  (:ivec3 "offset") (:float "bias"))
 ((:vec4 "textureOffset") (:sampler3D "sampler") (:vec3 "P")
  (:ivec3 "offset"))
 ((:ivec4 "textureOffset") (:isampler3D "sampler") (:vec3 "P")
  (:ivec3 "offset"))
 ((:uvec4 "textureOffset") (:usampler3D "sampler") (:vec3 "P")
  (:ivec3 "offset"))
 ((:vec4 "textureOffset") (:sampler2DRect "sampler") (:vec2 "P")
  (:ivec2 "offset"))
 ((:ivec4 "textureOffset") (:isampler2DRect "sampler") (:vec2 "P")
  (:ivec2 "offset"))
 ((:uvec4 "textureOffset") (:usampler2DRect "sampler") (:vec2 "P")
  (:ivec2 "offset"))
 ((:vec4 "textureOffset") (:sampler1DArray "sampler") (:vec2 "P")
  (:int "offset") (:float "bias"))
 ((:ivec4 "textureOffset") (:isampler1DArray "sampler") (:vec2 "P")
  (:int "offset") (:float "bias"))
 ((:uvec4 "textureOffset") (:usampler1DArray "sampler") (:vec2 "P")
  (:int "offset") (:float "bias"))
 ((:vec4 "textureOffset") (:sampler1DArray "sampler") (:vec2 "P")
  (:int "offset"))
 ((:ivec4 "textureOffset") (:isampler1DArray "sampler") (:vec2 "P")
  (:int "offset"))
 ((:uvec4 "textureOffset") (:usampler1DArray "sampler") (:vec2 "P")
  (:int "offset"))
 ((:vec4 "textureOffset") (:sampler2DArray "sampler") (:vec3 "P")
  (:ivec2 "offset") (:float "bias"))
 ((:ivec4 "textureOffset") (:isampler2DArray "sampler") (:vec3 "P")
  (:ivec2 "offset") (:float "bias"))
 ((:uvec4 "textureOffset") (:usampler2DArray "sampler") (:vec3 "P")
  (:ivec2 "offset") (:float "bias"))
 ((:vec4 "textureOffset") (:sampler2DArray "sampler") (:vec3 "P")
  (:ivec2 "offset"))
 ((:ivec4 "textureOffset") (:isampler2DArray "sampler") (:vec3 "P")
  (:ivec2 "offset"))
 ((:uvec4 "textureOffset") (:usampler2DArray "sampler") (:vec3 "P")
  (:ivec2 "offset"))
 ((:vec4 "texelFetch") (:sampler1D "sampler") (:int "P") (:int "lod"))
 ((:ivec4 "texelFetch") (:isampler1D "sampler") (:int "P")
  (:int "lod"))
 ((:uvec4 "texelFetch") (:usampler1D "sampler") (:int "P")
  (:int "lod"))
 ((:vec4 "texelFetch") (:sampler2D "sampler") (:ivec2 "P")
  (:int "lod"))
 ((:ivec4 "texelFetch") (:isampler2D "sampler") (:ivec2 "P")
  (:int "lod"))
 ((:uvec4 "texelFetch") (:usampler2D "sampler") (:ivec2 "P")
  (:int "lod"))
 ((:vec4 "texelFetch") (:sampler3D "sampler") (:ivec3 "P")
  (:int "lod"))
 ((:ivec4 "texelFetch") (:isampler3D "sampler") (:ivec3 "P")
  (:int "lod"))
 ((:uvec4 "texelFetch") (:usampler3D "sampler") (:ivec3 "P")
  (:int "lod"))
 ((:vec4 "texelFetch") (:sampler2DRect "sampler") (:ivec2 "P"))
 ((:ivec4 "texelFetch") (:isampler2DRect "sampler") (:ivec2 "P"))
 ((:uvec4 "texelFetch") (:usampler2DRect "sampler") (:ivec2 "P"))
 ((:vec4 "texelFetch") (:sampler1DArray "sampler") (:ivec2 "P")
  (:int "lod"))
 ((:ivec4 "texelFetch") (:isampler1DArray "sampler") (:ivec2 "P")
  (:int "lod"))
 ((:uvec4 "texelFetch") (:usampler1DArray "sampler") (:ivec2 "P")
  (:int "lod"))
 ((:vec4 "texelFetch") (:sampler2DArray "sampler") (:ivec3 "P")
  (:int "lod"))
 ((:ivec4 "texelFetch") (:isampler2DArray "sampler") (:ivec3 "P")
  (:int "lod"))
 ((:uvec4 "texelFetch") (:usampler2DArray "sampler") (:ivec3 "P")
  (:int "lod"))
 ((:vec4 "texelFetch") (:samplerBuffer "sampler") (:int "P"))
 ((:ivec4 "texelFetch") (:isamplerBuffer "sampler") (:int "P"))
 ((:uvec4 "texelFetch") (:usamplerBuffer "sampler") (:int "P"))
 ((:vec4 "texelFetch") (:sampler2DMS "sampler") (:ivec2 "P")
  (:int "sample"))
 ((:ivec4 "texelFetch") (:isampler2DMS "sampler") (:ivec2 "P")
  (:int "sample"))
 ((:uvec4 "texelFetch") (:usampler2DMS "sampler") (:ivec2 "P")
  (:int "sample"))
 ((:vec4 "texelFetch") (:sampler2DMSArray "sampler") (:ivec3 "P")
  (:int "sample"))
 ((:ivec4 "texelFetch") (:isampler2DMSArray "sampler") (:ivec3 "P")
  (:int "sample"))
 ((:uvec4 "texelFetch") (:usampler2DMSArray "sampler") (:ivec3 "P")
  (:int "sample"))
 ((:vec4 "texelFetchOffset") (:sampler1D "sampler") (:int "P")
  (:int "lod") (:int "offset"))
 ((:ivec4 "texelFetchOffset") (:isampler1D "sampler") (:int "P")
  (:int "lod") (:int "offset"))
 ((:uvec4 "texelFetchOffset") (:usampler1D "sampler") (:int "P")
  (:int "lod") (:int "offset"))
 ((:vec4 "texelFetchOffset") (:sampler2D "sampler") (:ivec2 "P")
  (:int "lod") (:ivec2 "offset"))
 ((:ivec4 "texelFetchOffset") (:isampler2D "sampler") (:ivec2 "P")
  (:int "lod") (:ivec2 "offset"))
 ((:uvec4 "texelFetchOffset") (:usampler2D "sampler") (:ivec2 "P")
  (:int "lod") (:ivec2 "offset"))
 ((:vec4 "texelFetchOffset") (:sampler3D "sampler") (:ivec3 "P")
  (:int "lod") (:ivec3 "offset"))
 ((:ivec4 "texelFetchOffset") (:isampler3D "sampler") (:ivec3 "P")
  (:int "lod") (:ivec3 "offset"))
 ((:uvec4 "texelFetchOffset") (:usampler3D "sampler") (:ivec3 "P")
  (:int "lod") (:ivec3 "offset"))
 ((:vec4 "texelFetchOffset") (:sampler2DRect "sampler") (:ivec2 "P")
  (:ivec2 "offset"))
 ((:ivec4 "texelFetchOffset") (:isampler2DRect "sampler") (:ivec2 "P")
  (:ivec2 "offset"))
 ((:uvec4 "texelFetchOffset") (:usampler2DRect "sampler") (:ivec2 "P")
  (:ivec2 "offset"))
 ((:vec4 "texelFetchOffset") (:sampler1DArray "sampler") (:ivec2 "P")
  (:int "lod") (:int "offset"))
 ((:ivec4 "texelFetchOffset") (:isampler1DArray "sampler") (:ivec2 "P")
  (:int "lod") (:int "offset"))
 ((:uvec4 "texelFetchOffset") (:usampler1DArray "sampler") (:ivec2 "P")
  (:int "lod") (:int "offset"))
 ((:vec4 "texelFetchOffset") (:sampler2DArray "sampler") (:ivec3 "P")
  (:int "lod") (:ivec2 "offset"))
 ((:ivec4 "texelFetchOffset") (:isampler2DArray "sampler") (:ivec3 "P")
  (:int "lod") (:ivec2 "offset"))
 ((:uvec4 "texelFetchOffset") (:usampler2DArray "sampler") (:ivec3 "P")
  (:int "lod") (:ivec2 "offset"))
 ((:vec4 "textureProjOffset") (:sampler1D "sampler") (:vec2 "P")
  (:int "offset") (:float "bias"))
 ((:ivec4 "textureProjOffset") (:isampler1D "sampler") (:vec2 "P")
  (:int "offset") (:float "bias"))
 ((:uvec4 "textureProjOffset") (:usampler1D "sampler") (:vec2 "P")
  (:int "offset") (:float "bias"))
 ((:vec4 "textureProjOffset") (:sampler1D "sampler") (:vec2 "P")
  (:int "offset"))
 ((:ivec4 "textureProjOffset") (:isampler1D "sampler") (:vec2 "P")
  (:int "offset"))
 ((:uvec4 "textureProjOffset") (:usampler1D "sampler") (:vec2 "P")
  (:int "offset"))
 ((:vec4 "textureProjOffset") (:sampler1D "sampler") (:vec4 "P")
  (:int "offset") (:float "bias"))
 ((:ivec4 "textureProjOffset") (:isampler1D "sampler") (:vec4 "P")
  (:int "offset") (:float "bias"))
 ((:uvec4 "textureProjOffset") (:usampler1D "sampler") (:vec4 "P")
  (:int "offset") (:float "bias"))
 ((:vec4 "textureProjOffset") (:sampler1D "sampler") (:vec4 "P")
  (:int "offset"))
 ((:ivec4 "textureProjOffset") (:isampler1D "sampler") (:vec4 "P")
  (:int "offset"))
 ((:uvec4 "textureProjOffset") (:usampler1D "sampler") (:vec4 "P")
  (:int "offset"))
 ((:vec4 "textureProjOffset") (:sampler2D "sampler") (:vec3 "P")
  (:ivec2 "offset") (:float "bias"))
 ((:ivec4 "textureProjOffset") (:isampler2D "sampler") (:vec3 "P")
  (:ivec2 "offset") (:float "bias"))
 ((:uvec4 "textureProjOffset") (:usampler2D "sampler") (:vec3 "P")
  (:ivec2 "offset") (:float "bias"))
 ((:vec4 "textureProjOffset") (:sampler2D "sampler") (:vec3 "P")
  (:ivec2 "offset"))
 ((:ivec4 "textureProjOffset") (:isampler2D "sampler") (:vec3 "P")
  (:ivec2 "offset"))
 ((:uvec4 "textureProjOffset") (:usampler2D "sampler") (:vec3 "P")
  (:ivec2 "offset"))
 ((:vec4 "textureProjOffset") (:sampler2D "sampler") (:vec4 "P")
  (:ivec2 "offset") (:float "bias"))
 ((:ivec4 "textureProjOffset") (:isampler2D "sampler") (:vec4 "P")
  (:ivec2 "offset") (:float "bias"))
 ((:uvec4 "textureProjOffset") (:usampler2D "sampler") (:vec4 "P")
  (:ivec2 "offset") (:float "bias"))
 ((:vec4 "textureProjOffset") (:sampler2D "sampler") (:vec4 "P")
  (:ivec2 "offset"))
 ((:ivec4 "textureProjOffset") (:isampler2D "sampler") (:vec4 "P")
  (:ivec2 "offset"))
 ((:uvec4 "textureProjOffset") (:usampler2D "sampler") (:vec4 "P")
  (:ivec2 "offset"))
 ((:vec4 "textureProjOffset") (:sampler3D "sampler") (:vec4 "P")
  (:ivec3 "offset") (:float "bias"))
 ((:ivec4 "textureProjOffset") (:isampler3D "sampler") (:vec4 "P")
  (:ivec3 "offset") (:float "bias"))
 ((:uvec4 "textureProjOffset") (:usampler3D "sampler") (:vec4 "P")
  (:ivec3 "offset") (:float "bias"))
 ((:vec4 "textureProjOffset") (:sampler3D "sampler") (:vec4 "P")
  (:ivec3 "offset"))
 ((:ivec4 "textureProjOffset") (:isampler3D "sampler") (:vec4 "P")
  (:ivec3 "offset"))
 ((:uvec4 "textureProjOffset") (:usampler3D "sampler") (:vec4 "P")
  (:ivec3 "offset"))
 ((:vec4 "textureProjOffset") (:sampler2DRect "sampler") (:vec3 "P")
  (:ivec2 "offset"))
 ((:ivec4 "textureProjOffset") (:isampler2DRect "sampler") (:vec3 "P")
  (:ivec2 "offset"))
 ((:uvec4 "textureProjOffset") (:usampler2DRect "sampler") (:vec3 "P")
  (:ivec2 "offset"))
 ((:vec4 "textureProjOffset") (:sampler2DRect "sampler") (:vec4 "P")
  (:ivec2 "offset"))
 ((:ivec4 "textureProjOffset") (:isampler2DRect "sampler") (:vec4 "P")
  (:ivec2 "offset"))
 ((:uvec4 "textureProjOffset") (:usampler2DRect "sampler") (:vec4 "P")
  (:ivec2 "offset"))
 ((:vec4 "textureLodOffset") (:sampler1D "sampler") (:float "P")
  (:float "lod") (:int "offset"))
 ((:ivec4 "textureLodOffset") (:isampler1D "sampler") (:float "P")
  (:float "lod") (:int "offset"))
 ((:uvec4 "textureLodOffset") (:usampler1D "sampler") (:float "P")
  (:float "lod") (:int "offset"))
 ((:vec4 "textureLodOffset") (:sampler2D "sampler") (:vec2 "P")
  (:float "lod") (:ivec2 "offset"))
 ((:ivec4 "textureLodOffset") (:isampler2D "sampler") (:vec2 "P")
  (:float "lod") (:ivec2 "offset"))
 ((:uvec4 "textureLodOffset") (:usampler2D "sampler") (:vec2 "P")
  (:float "lod") (:ivec2 "offset"))
 ((:vec4 "textureLodOffset") (:sampler3D "sampler") (:vec3 "P")
  (:float "lod") (:ivec3 "offset"))
 ((:ivec4 "textureLodOffset") (:isampler3D "sampler") (:vec3 "P")
  (:float "lod") (:ivec3 "offset"))
 ((:uvec4 "textureLodOffset") (:usampler3D "sampler") (:vec3 "P")
  (:float "lod") (:ivec3 "offset"))
 ((:vec4 "textureLodOffset") (:sampler1DArray "sampler") (:vec2 "P")
  (:float "lod") (:int "offset"))
 ((:ivec4 "textureLodOffset") (:isampler1DArray "sampler") (:vec2 "P")
  (:float "lod") (:int "offset"))
 ((:uvec4 "textureLodOffset") (:usampler1DArray "sampler") (:vec2 "P")
  (:float "lod") (:int "offset"))
 ((:vec4 "textureLodOffset") (:sampler2DArray "sampler") (:vec3 "P")
  (:float "lod") (:ivec2 "offset"))
 ((:ivec4 "textureLodOffset") (:isampler2DArray "sampler") (:vec3 "P")
  (:float "lod") (:ivec2 "offset"))
 ((:uvec4 "textureLodOffset") (:usampler2DArray "sampler") (:vec3 "P")
  (:float "lod") (:ivec2 "offset"))
 ((:vec4 "textureProjLod") (:sampler1D "sampler") (:vec2 "P")
  (:float "lod"))
 ((:ivec4 "textureProjLod") (:isampler1D "sampler") (:vec2 "P")
  (:float "lod"))
 ((:uvec4 "textureProjLod") (:usampler1D "sampler") (:vec2 "P")
  (:float "lod"))
 ((:vec4 "textureProjLod") (:sampler1D "sampler") (:vec4 "P")
  (:float "lod"))
 ((:ivec4 "textureProjLod") (:isampler1D "sampler") (:vec4 "P")
  (:float "lod"))
 ((:uvec4 "textureProjLod") (:usampler1D "sampler") (:vec4 "P")
  (:float "lod"))
 ((:vec4 "textureProjLod") (:sampler2D "sampler") (:vec3 "P")
  (:float "lod"))
 ((:ivec4 "textureProjLod") (:isampler2D "sampler") (:vec3 "P")
  (:float "lod"))
 ((:uvec4 "textureProjLod") (:usampler2D "sampler") (:vec3 "P")
  (:float "lod"))
 ((:vec4 "textureProjLod") (:sampler2D "sampler") (:vec4 "P")
  (:float "lod"))
 ((:ivec4 "textureProjLod") (:isampler2D "sampler") (:vec4 "P")
  (:float "lod"))
 ((:uvec4 "textureProjLod") (:usampler2D "sampler") (:vec4 "P")
  (:float "lod"))
 ((:vec4 "textureProjLod") (:sampler3D "sampler") (:vec4 "P")
  (:float "lod"))
 ((:ivec4 "textureProjLod") (:isampler3D "sampler") (:vec4 "P")
  (:float "lod"))
 ((:uvec4 "textureProjLod") (:usampler3D "sampler") (:vec4 "P")
  (:float "lod"))
 ((:vec4 "textureProjLodOffset") (:sampler1D "sampler") (:vec2 "P")
  (:float "lod") (:int "offset"))
 ((:ivec4 "textureProjLodOffset") (:isampler1D "sampler") (:vec2 "P")
  (:float "lod") (:int "offset"))
 ((:uvec4 "textureProjLodOffset") (:usampler1D "sampler") (:vec2 "P")
  (:float "lod") (:int "offset"))
 ((:vec4 "textureProjLodOffset") (:sampler1D "sampler") (:vec4 "P")
  (:float "lod") (:int "offset"))
 ((:ivec4 "textureProjLodOffset") (:isampler1D "sampler") (:vec4 "P")
  (:float "lod") (:int "offset"))
 ((:uvec4 "textureProjLodOffset") (:usampler1D "sampler") (:vec4 "P")
  (:float "lod") (:int "offset"))
 ((:vec4 "textureProjLodOffset") (:sampler2D "sampler") (:vec3 "P")
  (:float "lod") (:ivec2 "offset"))
 ((:ivec4 "textureProjLodOffset") (:isampler2D "sampler") (:vec3 "P")
  (:float "lod") (:ivec2 "offset"))
 ((:uvec4 "textureProjLodOffset") (:usampler2D "sampler") (:vec3 "P")
  (:float "lod") (:ivec2 "offset"))
 ((:vec4 "textureProjLodOffset") (:sampler2D "sampler") (:vec4 "P")
  (:float "lod") (:ivec2 "offset"))
 ((:ivec4 "textureProjLodOffset") (:isampler2D "sampler") (:vec4 "P")
  (:float "lod") (:ivec2 "offset"))
 ((:uvec4 "textureProjLodOffset") (:usampler2D "sampler") (:vec4 "P")
  (:float "lod") (:ivec2 "offset"))
 ((:vec4 "textureProjLodOffset") (:sampler3D "sampler") (:vec4 "P")
  (:float "lod") (:ivec3 "offset"))
 ((:ivec4 "textureProjLodOffset") (:isampler3D "sampler") (:vec4 "P")
  (:float "lod") (:ivec3 "offset"))
 ((:uvec4 "textureProjLodOffset") (:usampler3D "sampler") (:vec4 "P")
  (:float "lod") (:ivec3 "offset"))
 ((:vec4 "textureGrad") (:sampler1D "sampler") (:float "P")
  (:float "dPdx") (:float "dPdy"))
 ((:ivec4 "textureGrad") (:isampler1D "sampler") (:float "P")
  (:float "dPdx") (:float "dPdy"))
 ((:uvec4 "textureGrad") (:usampler1D "sampler") (:float "P")
  (:float "dPdx") (:float "dPdy"))
 ((:vec4 "textureGrad") (:sampler2D "sampler") (:vec2 "P")
  (:vec2 "dPdx") (:vec2 "dPdy"))
 ((:ivec4 "textureGrad") (:isampler2D "sampler") (:vec2 "P")
  (:vec2 "dPdx") (:vec2 "dPdy"))
 ((:uvec4 "textureGrad") (:usampler2D "sampler") (:vec2 "P")
  (:vec2 "dPdx") (:vec2 "dPdy"))
 ((:vec4 "textureGrad") (:sampler3D "sampler") (:vec3 "P")
  (:vec3 "dPdx") (:vec3 "dPdy"))
 ((:ivec4 "textureGrad") (:isampler3D "sampler") (:vec3 "P")
  (:vec3 "dPdx") (:vec3 "dPdy"))
 ((:uvec4 "textureGrad") (:usampler3D "sampler") (:vec3 "P")
  (:vec3 "dPdx") (:vec3 "dPdy"))
 ((:vec4 "textureGrad") (:samplerCube "sampler") (:vec3 "P")
  (:vec3 "dPdx") (:vec3 "dPdy"))
 ((:ivec4 "textureGrad") (:isamplerCube "sampler") (:vec3 "P")
  (:vec3 "dPdx") (:vec3 "dPdy"))
 ((:uvec4 "textureGrad") (:usamplerCube "sampler") (:vec3 "P")
  (:vec3 "dPdx") (:vec3 "dPdy"))
 ((:vec4 "textureGrad") (:sampler2DRect "sampler") (:vec2 "P")
  (:vec2 "dPdx") (:vec2 "dPdy"))
 ((:ivec4 "textureGrad") (:isampler2DRect "sampler") (:vec2 "P")
  (:vec2 "dPdx") (:vec2 "dPdy"))
 ((:uvec4 "textureGrad") (:usampler2DRect "sampler") (:vec2 "P")
  (:vec2 "dPdx") (:vec2 "dPdy"))
 ((:vec4 "textureGrad") (:sampler1DArray "sampler") (:vec2 "P")
  (:float "dPdx") (:float "dPdy"))
 ((:ivec4 "textureGrad") (:isampler1DArray "sampler") (:vec2 "P")
  (:float "dPdx") (:float "dPdy"))
 ((:uvec4 "textureGrad") (:usampler1DArray "sampler") (:vec2 "P")
  (:float "dPdx") (:float "dPdy"))
 ((:vec4 "textureGrad") (:sampler2DArray "sampler") (:vec3 "P")
  (:vec2 "dPdx") (:vec2 "dPdy"))
 ((:ivec4 "textureGrad") (:isampler2DArray "sampler") (:vec3 "P")
  (:vec2 "dPdx") (:vec2 "dPdy"))
 ((:uvec4 "textureGrad") (:usampler2DArray "sampler") (:vec3 "P")
  (:vec2 "dPdx") (:vec2 "dPdy"))
 ((:vec4 "textureGradOffset") (:sampler1D "sampler") (:float "P")
  (:float "dPdx") (:float "dPdy") (:int "offset"))
 ((:ivec4 "textureGradOffset") (:isampler1D "sampler") (:float "P")
  (:float "dPdx") (:float "dPdy") (:int "offset"))
 ((:uvec4 "textureGradOffset") (:usampler1D "sampler") (:float "P")
  (:float "dPdx") (:float "dPdy") (:int "offset"))
 ((:vec4 "textureGradOffset") (:sampler2D "sampler") (:vec2 "P")
  (:vec2 "dPdx") (:vec2 "dPdy") (:ivec2 "offset"))
 ((:ivec4 "textureGradOffset") (:isampler2D "sampler") (:vec2 "P")
  (:vec2 "dPdx") (:vec2 "dPdy") (:ivec2 "offset"))
 ((:uvec4 "textureGradOffset") (:usampler2D "sampler") (:vec2 "P")
  (:vec2 "dPdx") (:vec2 "dPdy") (:ivec2 "offset"))
 ((:vec4 "textureGradOffset") (:sampler3D "sampler") (:vec3 "P")
  (:vec3 "dPdx") (:vec3 "dPdy") (:ivec3 "offset"))
 ((:ivec4 "textureGradOffset") (:isampler3D "sampler") (:vec3 "P")
  (:vec3 "dPdx") (:vec3 "dPdy") (:ivec3 "offset"))
 ((:uvec4 "textureGradOffset") (:usampler3D "sampler") (:vec3 "P")
  (:vec3 "dPdx") (:vec3 "dPdy") (:ivec3 "offset"))
 ((:vec4 "textureGradOffset") (:sampler2DRect "sampler") (:vec2 "P")
  (:vec2 "dPdx") (:vec2 "dPdy") (:ivec2 "offset"))
 ((:ivec4 "textureGradOffset") (:isampler2DRect "sampler") (:vec2 "P")
  (:vec2 "dPdx") (:vec2 "dPdy") (:ivec2 "offset"))
 ((:uvec4 "textureGradOffset") (:usampler2DRect "sampler") (:vec2 "P")
  (:vec2 "dPdx") (:vec2 "dPdy") (:ivec2 "offset"))
 ((:vec4 "textureGradOffset") (:sampler1DArray "sampler") (:vec2 "P")
  (:float "dPdx") (:float "dPdy") (:int "offset"))
 ((:ivec4 "textureGradOffset") (:isampler1DArray "sampler") (:vec2 "P")
  (:float "dPdx") (:float "dPdy") (:int "offset"))
 ((:uvec4 "textureGradOffset") (:usampler1DArray "sampler") (:vec2 "P")
  (:float "dPdx") (:float "dPdy") (:int "offset"))
 ((:vec4 "textureGradOffset") (:sampler2DArray "sampler") (:vec3 "P")
  (:vec2 "dPdx") (:vec2 "dPdy") (:ivec2 "offset"))
 ((:ivec4 "textureGradOffset") (:isampler2DArray "sampler") (:vec3 "P")
  (:vec2 "dPdx") (:vec2 "dPdy") (:ivec2 "offset"))
 ((:uvec4 "textureGradOffset") (:usampler2DArray "sampler") (:vec3 "P")
  (:vec2 "dPdx") (:vec2 "dPdy") (:ivec2 "offset"))
 ((:vec4 "textureProjGrad") (:sampler1D "sampler") (:vec2 "P")
  (:float "dPdx") (:float "dPdy"))
 ((:ivec4 "textureProjGrad") (:isampler1D "sampler") (:vec2 "P")
  (:float "dPdx") (:float "dPdy"))
 ((:uvec4 "textureProjGrad") (:usampler1D "sampler") (:vec2 "P")
  (:float "dPdx") (:float "dPdy"))
 ((:vec4 "textureProjGrad") (:sampler1D "sampler") (:vec4 "P")
  (:float "dPdx") (:float "dPdy"))
 ((:ivec4 "textureProjGrad") (:isampler1D "sampler") (:vec4 "P")
  (:float "dPdx") (:float "dPdy"))
 ((:uvec4 "textureProjGrad") (:usampler1D "sampler") (:vec4 "P")
  (:float "dPdx") (:float "dPdy"))
 ((:vec4 "textureProjGrad") (:sampler2D "sampler") (:vec3 "P")
  (:vec2 "dPdx") (:vec2 "dPdy"))
 ((:ivec4 "textureProjGrad") (:isampler2D "sampler") (:vec3 "P")
  (:vec2 "dPdx") (:vec2 "dPdy"))
 ((:uvec4 "textureProjGrad") (:usampler2D "sampler") (:vec3 "P")
  (:vec2 "dPdx") (:vec2 "dPdy"))
 ((:vec4 "textureProjGrad") (:sampler2D "sampler") (:vec4 "P")
  (:vec2 "dPdx") (:vec2 "dPdy"))
 ((:ivec4 "textureProjGrad") (:isampler2D "sampler") (:vec4 "P")
  (:vec2 "dPdx") (:vec2 "dPdy"))
 ((:uvec4 "textureProjGrad") (:usampler2D "sampler") (:vec4 "P")
  (:vec2 "dPdx") (:vec2 "dPdy"))
 ((:vec4 "textureProjGrad") (:sampler3D "sampler") (:vec4 "P")
  (:vec3 "dPdx") (:vec3 "dPdy"))
 ((:ivec4 "textureProjGrad") (:isampler3D "sampler") (:vec4 "P")
  (:vec3 "dPdx") (:vec3 "dPdy"))
 ((:uvec4 "textureProjGrad") (:usampler3D "sampler") (:vec4 "P")
  (:vec3 "dPdx") (:vec3 "dPdy"))
 ((:vec4 "textureProjGrad") (:sampler2DRect "sampler") (:vec3 "P")
  (:vec2 "dPdx") (:vec2 "dPdy"))
 ((:ivec4 "textureProjGrad") (:isampler2DRect "sampler") (:vec3 "P")
  (:vec2 "dPdx") (:vec2 "dPdy"))
 ((:uvec4 "textureProjGrad") (:usampler2DRect "sampler") (:vec3 "P")
  (:vec2 "dPdx") (:vec2 "dPdy"))
 ((:vec4 "textureProjGrad") (:sampler2DRect "sampler") (:vec4 "P")
  (:vec2 "dPdx") (:vec2 "dPdy"))
 ((:ivec4 "textureProjGrad") (:isampler2DRect "sampler") (:vec4 "P")
  (:vec2 "dPdx") (:vec2 "dPdy"))
 ((:uvec4 "textureProjGrad") (:usampler2DRect "sampler") (:vec4 "P")
  (:vec2 "dPdx") (:vec2 "dPdy"))
 ((:vec4 "textureProjGradOffset") (:sampler1D "sampler") (:vec2 "P")
  (:float "dPdx") (:float "dPdy") (:int "offset"))
 ((:ivec4 "textureProjGradOffset") (:isampler1D "sampler") (:vec2 "P")
  (:float "dPdx") (:float "dPdy") (:int "offset"))
 ((:uvec4 "textureProjGradOffset") (:usampler1D "sampler") (:vec2 "P")
  (:float "dPdx") (:float "dPdy") (:int "offset"))
 ((:vec4 "textureProjGradOffset") (:sampler1D "sampler") (:vec4 "P")
  (:float "dPdx") (:float "dPdy") (:int "offset"))
 ((:ivec4 "textureProjGradOffset") (:isampler1D "sampler") (:vec4 "P")
  (:float "dPdx") (:float "dPdy") (:int "offset"))
 ((:uvec4 "textureProjGradOffset") (:usampler1D "sampler") (:vec4 "P")
  (:float "dPdx") (:float "dPdy") (:int "offset"))
 ((:vec4 "textureProjGradOffset") (:sampler2D "sampler") (:vec3 "P")
  (:vec2 "dPdx") (:vec2 "dPdy") (:vec2 "offset"))
 ((:ivec4 "textureProjGradOffset") (:isampler2D "sampler") (:vec3 "P")
  (:vec2 "dPdx") (:vec2 "dPdy") (:vec2 "offset"))
 ((:uvec4 "textureProjGradOffset") (:usampler2D "sampler") (:vec3 "P")
  (:vec2 "dPdx") (:vec2 "dPdy") (:vec2 "offset"))
 ((:vec4 "textureProjGradOffset") (:sampler2D "sampler") (:vec4 "P")
  (:vec2 "dPdx") (:vec2 "dPdy") (:vec2 "offset"))
 ((:ivec4 "textureProjGradOffset") (:isampler2D "sampler") (:vec4 "P")
  (:vec2 "dPdx") (:vec2 "dPdy") (:vec2 "offset"))
 ((:uvec4 "textureProjGradOffset") (:usampler2D "sampler") (:vec4 "P")
  (:vec2 "dPdx") (:vec2 "dPdy") (:vec2 "offset"))
 ((:vec4 "textureProjGradOffset") (:sampler2DRect "sampler") (:vec3 "P")
  (:vec2 "dPdx") (:vec2 "dPdy") (:ivec2 "offset"))
 ((:ivec4 "textureProjGradOffset") (:isampler2DRect "sampler")
  (:vec3 "P") (:vec2 "dPdx") (:vec2 "dPdy") (:ivec2 "offset"))
 ((:uvec4 "textureProjGradOffset") (:usampler2DRect "sampler")
  (:vec3 "P") (:vec2 "dPdx") (:vec2 "dPdy") (:ivec2 "offset"))
 ((:vec4 "textureProjGradOffset") (:sampler2DRect "sampler") (:vec4 "P")
  (:vec2 "dPdx") (:vec2 "dPdy") (:ivec2 "offset"))
 ((:ivec4 "textureProjGradOffset") (:isampler2DRect "sampler")
  (:vec4 "P") (:vec2 "dPdx") (:vec2 "dPdy") (:ivec2 "offset"))
 ((:uvec4 "textureProjGradOffset") (:usampler2DRect "sampler")
  (:vec4 "P") (:vec2 "dPdx") (:vec2 "dPdy") (:ivec2 "offset"))
 ((:vec4 "textureProjGradOffset") (:sampler3D "sampler") (:vec4 "P")
  (:vec3 "dPdx") (:vec3 "dPdy") (:vec3 "offset"))
 ((:ivec4 "textureProjGradOffset") (:isampler3D "sampler") (:vec4 "P")
  (:vec3 "dPdx") (:vec3 "dPdy") (:vec3 "offset"))
 ((:uvec4 "textureProjGradOffset") (:usampler3D "sampler") (:vec4 "P")
  (:vec3 "dPdx") (:vec3 "dPdy") (:vec3 "offset")))

;;expand optionals
(loop for func in funcs
   :append (if (loop for arg in (second func)
                  :if (listp (car arg))
                  :collect 1)
               (list (list (first func) (append (subseq (second func) 0
                                                        (1- (length (second func))))
                                                (car (last (second func)))))
                     (list (first func)
                           (subseq (second func) 0
                                   (1- (length (second func))))))
               (list func)))

;;cons in the first part
(loop for func in funcs collect (cons (first func) (second func)))

(loop for thing in funcs
   :append
     (if (some #'(lambda (x) (g-p (first x))) thing)
         (loop for i in '("" "i" "u")
            collect (loop for part in thing
                       :collect (if (g-p (first part))
                                    (list (format nil "~a~a" i (subseq (first part) 1))
                                          (second part))
                                    part)))
         (list thing)))


(defun mkstr (&rest args)
  (with-output-to-string (s)
    (dolist (a args) (princ a s))))

(defun symb (&rest args)
  (values (intern (apply #'mkstr args))))

(defun kwd (&rest args)
  (values (intern (apply #'mkstr args) "KEYWORD")))

(defun test ()
  (loop for thing in funcs
     collect `(glsl-defun :name ',(symb (string-upcase
                                         (cadar thing)))
                          :in-args ',(loop :for slot :in (rest thing)
                                        :collect (list (symb (second slot))
                                                       (kwd (string-upcase (first slot)))))
                          :output-type ',(varjo:flesh-out-type
                                          (kwd (string-upcase
                                                (caar (first funcs)))))
                          :transform ,(format nil "~a(~{~a~^,~^ ~})" (cadar thing)
                                              (loop for i below (length (rest thing))
                                                 collect "~a")))))

(defun g-p (string)
  (when (stringp string)
    (eq #\g (elt string 0))))


;; REALLY SHOULD USE THIS! vvvvvvvvv

;; VARJO> (symbol-munger:camel-case->lisp-symbol "theNewThing")
;; THE-NEW-THING
;; NIL
;; VARJO> (symbol-munger:lisp->camel-case 'the-dog-blah)
;; "theDogBlah"
